import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { KeyRound } from 'lucide-react';
import { getTokens } from '../api';
import ConfigExporter from '../components/ConfigExporter';
import { isAutoGeneratedToken } from '../utils/tokenForm';

export default function ApiConnect() {
  const { t } = useTranslation();
  const [tokens, setTokens] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    const load = async () => {
      try {
        const response = await getTokens();
        if (!cancelled && response.data.success) {
          setTokens((response.data.data || []).filter((token) => !isAutoGeneratedToken(token)));
        }
      } catch {
        // The shared API handler owns user-facing request errors.
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();
    return () => { cancelled = true; };
  }, []);

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-page-link/30 border-t-page-link" />
      </div>
    );
  }

  return (
    <div className="min-h-[calc(100dvh-64px)] bg-page-bg">
      <div className="mx-auto max-w-6xl px-4 pt-6 sm:px-6 lg:px-8">
        <header className="rounded-xl border border-page-divider bg-page-card-bg px-5 py-5 shadow-sm">
          <h1 className="text-2xl font-bold text-page">{t('nav.apiAccess')}</h1>
          <p className="mt-1 text-sm text-page-secondary">
            {t('apiAccess.quickConnectHint', { defaultValue: 'Choose a key and client to generate a connection config.' })}
          </p>
        </header>
      </div>

      <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8">
        {tokens.some((token) => Number(token.status) === 1) ? (
          <ConfigExporter tokens={tokens} />
        ) : (
          <div className="rounded-xl border border-page-divider bg-page-card-bg px-6 py-16 text-center shadow-sm">
            <div className="mx-auto flex h-11 w-11 items-center justify-center rounded-lg bg-page-surface text-page-muted">
              <KeyRound className="h-5 w-5" />
            </div>
            <p className="mt-4 text-sm font-semibold text-page">{t('config.noKeyPrompt')}</p>
            <p className="mt-1 text-xs text-page-muted">{t('config.noKeyDesc')}</p>
            <Link to="/api-keys" className="btn-primary mt-5 inline-flex items-center gap-2 !px-4 !py-2 text-xs">
              <KeyRound className="h-4 w-4" />
              {t('tokens.newKey')}
            </Link>
          </div>
        )}
      </main>
    </div>
  );
}
