import { useRef } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import DocsPageFrame, { useDocsActiveSection } from '../components/DocsLayout';
import { normalizeAppLanguage } from '../i18n/languageUtils';
import appStep1 from '../../picture/使用cc switch导入1.png';
import appStep2 from '../../picture/使用cc switch导入2.png';
import appStep3 from '../../picture/cc switch页面3.png';
import appStep4 from '../../picture/codex页面4.png';
import cliStep from '../../picture/codex-cli5-redacted.png';

const FILE_COMMANDS = `mkdir -p ~/.codex
test -f ~/.codex/config.toml && cp ~/.codex/config.toml ~/.codex/config.toml.bak
nano ~/.codex/config.toml`;

const PERMISSION_COMMANDS = `chmod 600 ~/.codex/config.toml
chmod 600 ~/.codex/auth.json`;

const COPY = {
  en: {
    title: 'Use Codex with a custom provider',
    description: 'Connect Codex to API-Route with CC Switch on Windows or macOS, or replace the Codex CLI configuration files manually on Linux.',
    directory: [['codex-app', 'Codex App'], ['codex-cli', 'Codex CLI']],
    closeLabel: 'Close image',
    app: {
      kicker: 'Windows / macOS',
      title: 'Use API-Route in the Codex App',
      body: 'The simplest setup is to import API-Route into Codex with CC Switch. It writes the selected API key, model, and endpoint into the Codex provider configuration for you.',
      downloadPrefix: 'Download ', downloadLink: 'CC Switch and Codex', accessPrefix: ', then open ', accessLink: 'API Access', accessSuffix: ' after signing in.',
      steps: [
        ['Choose the connection details', 'Select an active API key and a model currently available to that key. Choose an API route; use Global CDN if you are unsure. Keep the connection mode on CC Switch.'],
        ['Import into Codex', 'Set the target app to Codex, make sure CC Switch is already running, then select Import to CC Switch.'],
        ['Activate the provider', 'In CC Switch, open the Codex providers and switch the imported api-route provider to active.'],
        ['Check the Codex App', 'Open or restart Codex. The api-route provider should appear in the lower-left corner. Select a project and send a test request.'],
      ],
      captions: ['Select the API key, model, route, and CC Switch connection mode.', 'Choose Codex as the target and import the provider.', 'Activate the imported api-route provider in CC Switch.', 'Confirm that the Codex App is using api-route.'],
    },
    cli: {
      kicker: 'Linux',
      title: 'Use API-Route in Codex CLI',
      body: 'On Linux, use the manual Codex configuration generated by API-Route. The important step is to replace the complete ~/.codex/config.toml file with the generated config section.',
      preparePrefix: 'Sign in and open ', prepareLink: 'API Access', prepareSuffix: '. Select the API key, model, and route, switch to Manual config, choose Codex, then copy or download the generated configuration.',
      imageCaption: 'Choose Manual config and Codex to generate the required files. The API key is redacted in this screenshot.',
      configTitle: 'Replace config.toml',
      configSteps: [
        ['Back up the current file', 'Run the commands below. If config.toml exists, a config.toml.bak copy is created before the editor opens.'],
        ['Replace the whole file', 'In the generated result, copy everything after “# ~/.codex/config.toml” and before “# ~/.codex/auth.json”. Delete the old config.toml content, paste this section, and save. Do not merge old provider values into it.'],
        ['Write auth.json', 'Copy the JSON object shown after “# ~/.codex/auth.json” into ~/.codex/auth.json. Never commit or share this file because it contains your API key.'],
        ['Limit file access', 'After saving both files, restrict them to the current Linux user.'],
      ],
      fileCommands: FILE_COMMANDS,
      permissionCommands: PERMISSION_COMMANDS,
      commandsTitle: 'Common Codex CLI commands',
      commands: [
        ['codex', 'Start an interactive session in the current directory.'],
        ['codex "Explain this repository"', 'Start an interactive session with an initial instruction.'],
        ['codex -C /path/to/project', 'Start Codex with another directory as the working root.'],
        ['codex resume', 'Choose and continue a previous interactive session.'],
        ['codex resume --last', 'Continue the most recent session in the current working directory.'],
        ['codex exec "Run tests and summarize failures"', 'Run one non-interactive task and print the result.'],
        ['codex doctor', 'Diagnose local installation, configuration, authentication, and runtime issues.'],
        ['codex --help', 'Show commands and options.'],
        ['codex --version', 'Show the installed Codex CLI version.'],
      ],
      verify: 'Run codex after replacing the files. If the provider or model is wrong, return to API Access and generate a fresh configuration instead of guessing the endpoint or model ID.',
    },
  },
  zh: {
    title: '为 Codex 配置自定义供应商',
    description: '在 Windows 或 macOS 上通过 CC Switch 将 Codex 接入 API-Route，或在 Linux 上手动替换 Codex CLI 配置文件。',
    directory: [['codex-app', 'Codex App'], ['codex-cli', 'Codex CLI']],
    closeLabel: '关闭大图',
    app: {
      kicker: 'Windows / macOS',
      title: '在 Codex App 中使用 API-Route',
      body: '最简单的方式是使用 CC Switch 一键导入。它会把你选择的 API Key、模型和调用节点写入 Codex 的供应商配置。',
      downloadPrefix: '先从站内下载并安装', downloadLink: 'CC Switch 和 Codex', accessPrefix: '，登录后打开', accessLink: 'API 接入', accessSuffix: '。',
      steps: [
        ['选择接入信息', '选择一个已启用的 API Key，以及该密钥当前可用的模型。再选择调用节点；如果不知道如何选择，使用 Global CDN。连接方式保持为 CC Switch。'],
        ['导入 Codex', '目标应用选择 Codex，确认 CC Switch 已经打开，然后点击“一键导入到 CC Switch”。'],
        ['启用供应商', '进入 CC Switch 的 Codex 供应商列表，把刚导入的 api-route 供应商切换为“使用中”。'],
        ['检查 Codex App', '打开或重启 Codex。左下角应显示 api-route。选择项目并发送一条测试请求，正常回复即表示配置完成。'],
      ],
      captions: ['选择 API Key、模型、调用节点和 CC Switch 接入方式。', '目标应用选择 Codex，然后一键导入。', '在 CC Switch 中启用导入的 api-route 供应商。', '确认 Codex App 左下角正在使用 api-route。'],
    },
    cli: {
      kicker: 'Linux',
      title: '在 Codex CLI 中使用 API-Route',
      body: 'Linux 推荐使用 API-Route 生成的 Codex 手动配置。关键步骤是用生成的配置完整替换 ~/.codex/config.toml，而不是只改其中某一行。',
      preparePrefix: '登录后打开', prepareLink: 'API 接入', prepareSuffix: '，依次选择 API Key、模型和调用节点，切换到“手动配置”，工具选择 Codex，然后复制或下载生成的配置。',
      imageCaption: '切换到手动配置并选择 Codex，生成所需文件。截图中的 API Key 已脱敏。',
      configTitle: '替换 config.toml',
      configSteps: [
        ['备份原文件', '先运行下面的命令。如果 config.toml 已存在，会在打开编辑器前生成 config.toml.bak 备份。'],
        ['完整替换文件', '在生成结果中，复制“# ~/.codex/config.toml”之后、“# ~/.codex/auth.json”之前的全部内容。清空旧 config.toml，粘贴这一段并保存，不要把旧供应商字段混进新配置。'],
        ['写入 auth.json', '把“# ~/.codex/auth.json”之后的 JSON 对象保存到 ~/.codex/auth.json。该文件包含 API Key，禁止提交到 Git 或发送给他人。'],
        ['限制文件权限', '两个文件保存完成后，只允许当前 Linux 用户读取和修改。'],
      ],
      fileCommands: FILE_COMMANDS,
      permissionCommands: PERMISSION_COMMANDS,
      commandsTitle: 'Codex CLI 常用命令',
      commands: [
        ['codex', '在当前目录启动交互式会话。'],
        ['codex "解释这个仓库"', '带一条初始指令启动交互式会话。'],
        ['codex -C /path/to/project', '指定另一个目录作为工作目录。'],
        ['codex resume', '选择并继续以前的交互式会话。'],
        ['codex resume --last', '继续当前工作目录最近一次会话。'],
        ['codex exec "运行测试并总结失败项"', '非交互执行一次任务并输出结果。'],
        ['codex doctor', '诊断本地安装、配置、鉴权和运行环境问题。'],
        ['codex --help', '查看命令与选项。'],
        ['codex --version', '查看当前安装的 Codex CLI 版本。'],
      ],
      verify: '替换文件后运行 codex 测试。如果供应商或模型不正确，请返回 API 接入重新生成配置，不要猜测调用地址或模型 ID。',
    },
  },
  ja: {
    title: 'Codex でカスタムプロバイダーを使う',
    description: 'Windows または macOS では CC Switch、Linux では Codex CLI の設定ファイルを使って Codex を API-Route に接続します。',
    directory: [['codex-app', 'Codex App'], ['codex-cli', 'Codex CLI']],
    closeLabel: '画像を閉じる',
    app: {
      kicker: 'Windows / macOS',
      title: 'Codex App で API-Route を使う',
      body: '最も簡単なのは CC Switch のワンクリック取り込みです。選択した API キー、モデル、接続先が Codex のプロバイダー設定に反映されます。',
      downloadPrefix: 'サイト内から', downloadLink: 'CC Switch と Codex をダウンロード', accessPrefix: 'し、ログイン後に', accessLink: 'API 連携', accessSuffix: 'を開きます。',
      steps: [
        ['接続情報を選ぶ', '有効な API キーと、そのキーで現在利用できるモデルを選びます。接続先に迷う場合は Global CDN を選び、接続方法は CC Switch のままにします。'],
        ['Codex に取り込む', '対象アプリを Codex に設定し、CC Switch が起動していることを確認してから取り込みを実行します。'],
        ['プロバイダーを有効にする', 'CC Switch の Codex プロバイダー一覧で、取り込んだ api-route を「使用中」に切り替えます。'],
        ['Codex App を確認する', 'Codex を開くか再起動します。左下に api-route が表示されたら、プロジェクトを選んでテストメッセージを送ります。'],
      ],
      captions: ['API キー、モデル、接続先、CC Switch を選択します。', '対象を Codex にして取り込みます。', 'CC Switch で api-route を有効にします。', 'Codex App が api-route を使用していることを確認します。'],
    },
    cli: {
      kicker: 'Linux', title: 'Codex CLI で API-Route を使う',
      body: 'Linux では API-Route が生成する手動設定を使います。生成された設定セクションで ~/.codex/config.toml 全体を置き換えることが重要です。',
      preparePrefix: 'ログイン後に', prepareLink: 'API 連携', prepareSuffix: 'を開き、API キー、モデル、接続先を選びます。「手動設定」に切り替え、ツールを Codex にして設定をコピーまたはダウンロードします。',
      imageCaption: '手動設定で Codex を選び、必要なファイルを生成します。画面内の API キーはマスク済みです。',
      configTitle: 'config.toml を置き換える',
      configSteps: [
        ['既存ファイルをバックアップ', '以下のコマンドを実行します。config.toml がある場合は、エディターを開く前に config.toml.bak を作成します。'],
        ['ファイル全体を置き換える', '生成結果の「# ~/.codex/config.toml」から「# ~/.codex/auth.json」の直前までをコピーします。古い内容を削除し、このセクションだけを貼り付けて保存します。'],
        ['auth.json を保存する', '「# ~/.codex/auth.json」の後にある JSON を ~/.codex/auth.json に保存します。API キーを含むため、Git への追加や共有は禁止です。'],
        ['権限を制限する', '保存後、両方のファイルを現在の Linux ユーザーだけが読み書きできるようにします。'],
      ],
      fileCommands: FILE_COMMANDS, permissionCommands: PERMISSION_COMMANDS,
      commandsTitle: 'Codex CLI の主なコマンド',
      commands: [
        ['codex', '現在のディレクトリで対話セッションを開始します。'], ['codex "このリポジトリを説明して"', '最初の指示付きで対話セッションを開始します。'], ['codex -C /path/to/project', '別のディレクトリを作業ルートに指定します。'], ['codex resume', '以前の対話セッションを選んで再開します。'], ['codex resume --last', '現在の作業ディレクトリで直近のセッションを再開します。'], ['codex exec "テストを実行して失敗を要約して"', '非対話で 1 件のタスクを実行します。'], ['codex doctor', 'インストール、設定、認証、実行環境を診断します。'], ['codex --help', 'コマンドとオプションを表示します。'], ['codex --version', 'インストール済みのバージョンを表示します。'],
      ],
      verify: 'ファイルを置き換えたら codex を実行します。プロバイダーやモデルが違う場合は、接続先やモデル ID を推測せず、API 連携で設定を再生成してください。',
    },
  },
  ko: {
    title: 'Codex에서 사용자 지정 공급자 사용하기',
    description: 'Windows 또는 macOS에서는 CC Switch로, Linux에서는 Codex CLI 설정 파일을 교체해 Codex를 API-Route에 연결합니다.',
    directory: [['codex-app', 'Codex App'], ['codex-cli', 'Codex CLI']],
    closeLabel: '큰 이미지 닫기',
    app: {
      kicker: 'Windows / macOS', title: 'Codex App에서 API-Route 사용하기',
      body: '가장 간단한 방법은 CC Switch 원클릭 가져오기입니다. 선택한 API 키, 모델, 엔드포인트가 Codex 공급자 설정에 자동으로 반영됩니다.',
      downloadPrefix: '사이트에서 ', downloadLink: 'CC Switch와 Codex를 다운로드', accessPrefix: '한 뒤 로그인하고 ', accessLink: 'API 연결', accessSuffix: '을 여세요.',
      steps: [
        ['연결 정보 선택', '활성 API 키와 해당 키에서 현재 사용할 수 있는 모델을 선택합니다. 엔드포인트가 확실하지 않으면 Global CDN을 사용하고 연결 방식은 CC Switch로 유지하세요.'],
        ['Codex로 가져오기', '대상 앱을 Codex로 설정하고 CC Switch가 실행 중인지 확인한 다음 가져오기를 실행합니다.'],
        ['공급자 활성화', 'CC Switch의 Codex 공급자 목록에서 가져온 api-route 공급자를 사용 중으로 전환합니다.'],
        ['Codex App 확인', 'Codex를 열거나 다시 시작합니다. 왼쪽 아래에 api-route가 표시되면 프로젝트를 선택하고 테스트 요청을 보내세요.'],
      ],
      captions: ['API 키, 모델, 엔드포인트와 CC Switch 방식을 선택합니다.', '대상 앱을 Codex로 선택해 가져옵니다.', 'CC Switch에서 api-route 공급자를 활성화합니다.', 'Codex App이 api-route를 사용 중인지 확인합니다.'],
    },
    cli: {
      kicker: 'Linux', title: 'Codex CLI에서 API-Route 사용하기',
      body: 'Linux에서는 API-Route가 생성한 수동 설정을 사용합니다. 생성된 설정 섹션으로 ~/.codex/config.toml 전체를 교체하는 것이 핵심입니다.',
      preparePrefix: '로그인 후 ', prepareLink: 'API 연결', prepareSuffix: '을 열고 API 키, 모델, 엔드포인트를 선택하세요. 수동 설정으로 전환하고 도구는 Codex를 선택한 뒤 생성된 설정을 복사하거나 다운로드합니다.',
      imageCaption: '수동 설정과 Codex를 선택해 필요한 파일을 생성합니다. 화면의 API 키는 마스킹했습니다.',
      configTitle: 'config.toml 교체하기',
      configSteps: [
        ['기존 파일 백업', '아래 명령을 실행하세요. config.toml이 있으면 편집기를 열기 전에 config.toml.bak으로 복사합니다.'],
        ['파일 전체 교체', '생성 결과에서 “# ~/.codex/config.toml” 다음부터 “# ~/.codex/auth.json” 직전까지 복사합니다. 기존 내용을 지우고 이 섹션만 붙여 넣어 저장하세요.'],
        ['auth.json 저장', '“# ~/.codex/auth.json” 다음의 JSON 객체를 ~/.codex/auth.json에 저장합니다. API 키가 포함되므로 Git에 커밋하거나 공유하지 마세요.'],
        ['파일 권한 제한', '두 파일을 저장한 뒤 현재 Linux 사용자만 읽고 쓸 수 있도록 제한합니다.'],
      ],
      fileCommands: FILE_COMMANDS, permissionCommands: PERMISSION_COMMANDS,
      commandsTitle: '자주 사용하는 Codex CLI 명령',
      commands: [
        ['codex', '현재 디렉터리에서 대화형 세션을 시작합니다.'], ['codex "이 저장소를 설명해 줘"', '초기 지시와 함께 대화형 세션을 시작합니다.'], ['codex -C /path/to/project', '다른 디렉터리를 작업 루트로 지정합니다.'], ['codex resume', '이전 대화형 세션을 선택해 계속합니다.'], ['codex resume --last', '현재 작업 디렉터리의 최근 세션을 계속합니다.'], ['codex exec "테스트를 실행하고 실패를 요약해 줘"', '비대화형으로 작업 하나를 실행합니다.'], ['codex doctor', '설치, 설정, 인증, 실행 환경 문제를 진단합니다.'], ['codex --help', '명령과 옵션을 표시합니다.'], ['codex --version', '설치된 Codex CLI 버전을 표시합니다.'],
      ],
      verify: '파일을 교체한 뒤 codex를 실행하세요. 공급자나 모델이 잘못되었다면 엔드포인트나 모델 ID를 추측하지 말고 API 연결에서 설정을 다시 생성하세요.',
    },
  },
};

function SectionHeading({ kicker, title, body }) {
  return (
    <div className="max-w-3xl">
      <p className="text-xs font-bold uppercase tracking-[0.18em] text-page-link">{kicker}</p>
      <h2 className="mt-3 text-2xl font-bold tracking-[-0.03em] text-page sm:text-3xl">{title}</h2>
      <p className="mt-3 text-sm leading-7 text-page-secondary sm:text-base">{body}</p>
    </div>
  );
}

function Step({ number, title, body }) {
  return (
    <div className="grid gap-3 border-t border-page-divider py-5 sm:grid-cols-[36px_180px_1fr] sm:gap-5">
      <span className="text-sm font-bold tabular-nums text-page-link">{String(number).padStart(2, '0')}</span>
      <h3 className="text-sm font-bold text-page">{title}</h3>
      <p className="text-sm leading-6 text-page-secondary">{body}</p>
    </div>
  );
}

function Screenshot({ alt, caption, closeLabel, src }) {
  const dialogRef = useRef(null);

  return (
    <figure className="mb-8">
      <button type="button" onClick={() => dialogRef.current?.showModal()} className="block w-full cursor-zoom-in rounded-md text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-page-link/40">
        <img src={src} alt={alt} loading="lazy" className="w-full rounded-md border border-page-divider bg-page-card-bg" />
      </button>
      <figcaption className="mt-2 text-xs leading-5 text-page-secondary">{caption}</figcaption>
      <dialog
        ref={dialogRef}
        aria-label={alt}
        onClick={(event) => event.target === event.currentTarget && dialogRef.current?.close()}
        className="m-auto max-h-none max-w-none bg-transparent p-0 backdrop:bg-black/80"
      >
        <div className="relative p-5">
          <button
            type="button"
            aria-label={closeLabel}
            onClick={() => dialogRef.current?.close()}
            className="absolute right-7 top-7 flex h-10 w-10 items-center justify-center rounded-full bg-black/70 text-2xl leading-none text-white hover:bg-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"
          >
            ×
          </button>
          <img src={src} alt={alt} className="max-h-[calc(100dvh-2.5rem)] max-w-[calc(100vw-2.5rem)] object-contain" />
        </div>
      </dialog>
    </figure>
  );
}

function CodeBlock({ children }) {
  return (
    <pre className="mb-6 overflow-x-auto rounded-md border border-[#4A342A] bg-[#211814] p-4 text-xs leading-6 text-[#F5EDE7] sm:text-sm">
      <code>{children}</code>
    </pre>
  );
}

export default function DocsCodexCustomProvider() {
  const { i18n } = useTranslation();
  const language = normalizeAppLanguage(i18n.resolvedLanguage || i18n.language);
  const copy = COPY[language] || COPY.en;
  const activeSection = useDocsActiveSection(copy.directory);
  const appImages = [appStep1, appStep2, appStep3, appStep4];

  return (
    <DocsPageFrame activeSection={activeSection} directory={copy.directory}>
      <header className="border-b border-page-divider pb-8">
        <h1 className="text-3xl font-bold tracking-[-0.04em] text-page sm:text-4xl">{copy.title}</h1>
        <p className="mt-3 max-w-3xl text-sm leading-7 text-page-secondary sm:text-base">{copy.description}</p>
      </header>

      <section id="codex-app" className="scroll-mt-28">
        <SectionHeading {...copy.app} />
        <p className="mt-5 text-sm leading-7 text-page-secondary">
          {copy.app.downloadPrefix}<Link to="/clients" className="font-bold text-page-link hover:underline">{copy.app.downloadLink}</Link>
          {copy.app.accessPrefix}<Link to="/api-connect" className="font-bold text-page-link hover:underline">{copy.app.accessLink}</Link>{copy.app.accessSuffix}
        </p>
        <div className="mt-7 border-b border-page-divider">
          {copy.app.steps.map(([title, body], index) => (
            <div key={title}>
              <Step number={index + 1} title={title} body={body} />
              <Screenshot src={appImages[index]} alt={copy.app.captions[index]} caption={copy.app.captions[index]} closeLabel={copy.closeLabel} />
            </div>
          ))}
        </div>
      </section>

      <section id="codex-cli" className="scroll-mt-28">
        <SectionHeading {...copy.cli} />
        <p className="mt-5 text-sm leading-7 text-page-secondary">
          {copy.cli.preparePrefix}<Link to="/api-connect" className="font-bold text-page-link hover:underline">{copy.cli.prepareLink}</Link>{copy.cli.prepareSuffix}
        </p>
        <Screenshot src={cliStep} alt={copy.cli.imageCaption} caption={copy.cli.imageCaption} closeLabel={copy.closeLabel} />

        <h3 className="mt-10 text-lg font-bold tracking-[-0.02em] text-page sm:text-xl">{copy.cli.configTitle}</h3>
        <div className="mt-5 border-b border-page-divider">
          {copy.cli.configSteps.map(([title, body], index) => (
            <div key={title}>
              <Step number={index + 1} title={title} body={body} />
              {index === 0 && <CodeBlock>{copy.cli.fileCommands}</CodeBlock>}
              {index === 3 && <CodeBlock>{copy.cli.permissionCommands}</CodeBlock>}
            </div>
          ))}
        </div>

        <h3 className="mt-10 text-lg font-bold tracking-[-0.02em] text-page sm:text-xl">{copy.cli.commandsTitle}</h3>
        <dl className="mt-5 divide-y divide-page-divider border-y border-page-divider">
          {copy.cli.commands.map(([command, description]) => (
            <div key={command} className="grid gap-2 py-4 sm:grid-cols-[280px_1fr] sm:gap-6">
              <dt><code className="break-all text-sm text-page-link">{command}</code></dt>
              <dd className="text-sm leading-6 text-page-secondary">{description}</dd>
            </div>
          ))}
        </dl>
        <p className="mt-5 border-l-2 border-page-divider pl-4 text-sm leading-6 text-page-secondary">{copy.cli.verify}</p>
      </section>
    </DocsPageFrame>
  );
}
