import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getTokens } from '../api';
import WebChat from '../components/WebChat';

const isAutoGeneratedToken = (token) => /-auto-\d+$/.test(token.name || '');

export default function QuickStart() {
  const navigate = useNavigate();
  const [tokens, setTokens] = useState([]);
  const [loading, setLoading] = useState(true);
  const visibleTokens = useMemo(
    () => tokens.filter((token) => !isAutoGeneratedToken(token)),
    [tokens],
  );

  useEffect(() => {
    getTokens()
      .then((response) => {
        if (response.data.success) setTokens(response.data.data || []);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex min-h-[calc(100dvh-4rem)] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-page-link/30 border-t-page-link" />
      </div>
    );
  }

  return (
    <WebChat
      tokens={visibleTokens}
      onOpenLocalSetup={() => navigate('/api-keys')}
    />
  );
}
