import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  ChevronDown,
  Copy,
  KeyRound,
  ListChecks,
  Pencil,
  Plus,
  ShieldCheck,
  Trash2,
} from 'lucide-react';
import {
  Q,
  createToken,
  deleteToken,
  getSiteKeyGroups,
  getSiteKeyGroupPricing,
  getSiteModels,
  getTokenSupportedModels,
  getTokens,
  updateToken,
} from '../api';
import DateTimePicker from '../components/DateTimePicker';
import { useCurrency } from '../context/SiteContext';
import {
  buildTokenPayload,
  createTokenForm,
  isAutoGeneratedToken,
  timestampToLocalInput,
} from '../utils/tokenForm';
import { trackEvent } from '../utils/analytics';
import toast from 'react-hot-toast';

function getTokenSecret(token) {
  const value = String(token?.key || '');
  if (!value) return '';
  return value.startsWith('sk-') ? value : `sk-${value}`;
}

function getTokenPreview(token) {
  const secret = getTokenSecret(token);
  if (!secret) return '-';
  if (secret.length <= 16) return `${secret.slice(0, 7)}...`;
  return `${secret.slice(0, 10)}...${secret.slice(-4)}`;
}

function formatTokenDate(timestamp) {
  if (!timestamp) return '';
  return new Date(timestamp * 1000).toLocaleDateString();
}

function parseGroupTags(tags) {
  if (Array.isArray(tags)) return tags.filter(Boolean);
  try {
    const parsed = JSON.parse(tags || '[]');
    return Array.isArray(parsed) ? parsed.filter(Boolean) : [];
  } catch {
    return [];
  }
}

export default function Tokens() {
  const { t } = useTranslation();
  const { symbol, rate, cnyRate } = useCurrency();
  const [tokens, setTokens] = useState([]);
  const [loading, setLoading] = useState(true);
  const [copiedId, setCopiedId] = useState(null);
  const [newKey, setNewKey] = useState(null);
  const [deleteConfirm, setDeleteConfirm] = useState(null);
  const [expandedTokens, setExpandedTokens] = useState({});
  const [tokenModels, setTokenModels] = useState({});
  const [keyGroups, setKeyGroups] = useState([]);
  const [activePricingGroup, setActivePricingGroup] = useState(null);
  const [groupPricingCache, setGroupPricingCache] = useState({});
  const [loadingGroupPricingId, setLoadingGroupPricingId] = useState(0);
  const [groupPricingSearch, setGroupPricingSearch] = useState('');
  const [tokenDialog, setTokenDialog] = useState(null);
  const [tokenForm, setTokenForm] = useState(() => createTokenForm());
  const [initialTokenForm, setInitialTokenForm] = useState(() => createTokenForm());
  const [submittingToken, setSubmittingToken] = useState(false);
  const [availableModels, setAvailableModels] = useState([]);
  const [loadingModels, setLoadingModels] = useState(false);
  const [modelsLoaded, setModelsLoaded] = useState(false);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [tokensRes, groupsRes] = await Promise.all([
        getTokens(),
        getSiteKeyGroups().catch(() => ({ data: { success: false } })),
      ]);
      if (tokensRes.data.success) setTokens(tokensRes.data.data || []);
      if (groupsRes.data.success) setKeyGroups(groupsRes.data.data || []);
    } catch {
      // The shared API handler owns user-facing request errors.
    }
    setLoading(false);
  }, []);

  useEffect(() => {
    load();
    window.addEventListener('tokens:changed', load);
    return () => window.removeEventListener('tokens:changed', load);
  }, [load]);

  const groupedByVendor = useMemo(() => {
    const groups = {};
    keyGroups.forEach((group) => {
      const vendor = group.vendor_category || t('tokens.otherGroups');
      if (!groups[vendor]) groups[vendor] = [];
      groups[vendor].push(group);
    });
    return groups;
  }, [keyGroups, t]);

  const visibleTokens = useMemo(
    () => tokens.filter((token) => !isAutoGeneratedToken(token)),
    [tokens],
  );

  const openTokenDialog = (token, group) => {
    const form = createTokenForm(token || {
      name: group?.name || '',
      key_group_id: group?.id || 0,
    });
    setTokenForm(form);
    setInitialTokenForm(form);
    setTokenDialog({ token: token || null, group: group || null });
  };

  const openCreateDefault = () => openTokenDialog(null, null);

  const openCreateFromGroup = (group) => {
    if (group.is_unavailable) return;
    openTokenDialog(null, group);
  };

  const openEdit = (token) => {
    const group = keyGroups.find((item) => item.id === Number(token.key_group_id)) || null;
    openTokenDialog(token, group);
  };

  const closeTokenDialog = () => {
    setTokenDialog(null);
    setSubmittingToken(false);
  };

  const loadAvailableModels = useCallback(async () => {
    if (modelsLoaded || loadingModels) return;
    setLoadingModels(true);
    try {
      const response = await getSiteModels();
      if (response.data.success) {
        setAvailableModels([...new Set(
          (response.data.data || [])
            .filter((model) => model.enabled !== false)
            .map((model) => model.model_name)
            .filter(Boolean),
        )]);
        setModelsLoaded(true);
      }
    } catch {
      // The shared API handler owns user-facing request errors.
    }
    setLoadingModels(false);
  }, [loadingModels, modelsLoaded]);

  const openGroupPricing = async (group) => {
    setActivePricingGroup(group);
    setGroupPricingSearch('');
    if (groupPricingCache[group.id] || loadingGroupPricingId === group.id) return;

    setLoadingGroupPricingId(group.id);
    try {
      const response = await getSiteKeyGroupPricing(group.id);
      if (response.data.success) {
        setGroupPricingCache((current) => ({
          ...current,
          [group.id]: response.data.data || { items: [], summary: null, group },
        }));
      }
    } catch {
      // The shared API handler owns user-facing request errors.
    }
    setLoadingGroupPricingId(0);
  };

  const closeGroupPricing = () => {
    setActivePricingGroup(null);
    setGroupPricingSearch('');
  };

  const handleTokenSubmit = async (event) => {
    event.preventDefault();
    if (!tokenForm.name.trim()) {
      toast.error(t('tokens.enterName'));
      return;
    }
    setSubmittingToken(true);
    try {
      const editingToken = tokenDialog?.token;
      const payload = buildTokenPayload(tokenForm, initialTokenForm, {
        includeGroup: !editingToken,
      });
      const response = editingToken
        ? await updateToken(editingToken.id, payload)
        : await createToken(payload);
      if (response.data.success) {
        if (editingToken) {
          toast.success(t('tokens.tokenUpdated'));
        } else {
          trackEvent('api_key_created', {
            source: tokenDialog?.group ? 'key_group' : 'manual',
          });
          if (response.data.data?.key) setNewKey(response.data.data.key);
        }
        closeTokenDialog();
        await load();
      }
    } catch {
      // The shared API handler owns user-facing request errors.
    }
    setSubmittingToken(false);
  };

  const handleToggle = async (token) => {
    try {
      const response = await updateToken(token.id, {
        status: Number(token.status) === 1 ? 2 : 1,
      });
      if (response.data.success) {
        toast.success(Number(token.status) === 1 ? t('tokens.tokenDisabled') : t('tokens.tokenEnabled'));
        await load();
      }
    } catch {
      // The shared API handler owns user-facing request errors.
    }
  };

  const handleDelete = async () => {
    if (!deleteConfirm) return;
    try {
      const response = await deleteToken(deleteConfirm.id);
      if (response.data.success) {
        toast.success(t('tokens.tokenDeleted'));
        setDeleteConfirm(null);
        await load();
      }
    } catch {
      // The shared API handler owns user-facing request errors.
    }
  };

  const handleCopy = async (text) => {
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    setCopiedId(text);
    toast.success(t('tokens.copiedToClipboard'));
    window.setTimeout(() => setCopiedId(null), 2000);
  };

  const handleToggleSupportedModels = async (tokenId) => {
    const expanded = Boolean(expandedTokens[tokenId]);
    setExpandedTokens((current) => ({ ...current, [tokenId]: !expanded }));
    if (expanded) return;

    setTokenModels((current) => ({
      ...current,
      [tokenId]: {
        loading: true,
        models: [],
        count: 0,
        provider_names: [],
        restricted_by_providers: false,
        restricted_by_models: false,
      },
    }));
    try {
      const response = await getTokenSupportedModels(tokenId);
      if (response.data.success) {
        const data = response.data.data || {};
        setTokenModels((current) => ({
          ...current,
          [tokenId]: {
            loading: false,
            models: data.models || [],
            count: data.count || 0,
            provider_names: data.provider_names || [],
            restricted_by_providers: Boolean(data.restricted_by_providers),
            restricted_by_models: Boolean(data.restricted_by_models),
          },
        }));
      } else {
        throw new Error('Unable to load supported models');
      }
    } catch {
      setTokenModels((current) => ({
        ...current,
        [tokenId]: {
          loading: false,
          error: true,
          models: [],
          count: 0,
          provider_names: [],
          restricted_by_providers: false,
          restricted_by_models: false,
        },
      }));
    }
  };

  const hasGroups = keyGroups.length > 0;
  const activeGroupPricing = activePricingGroup
    ? groupPricingCache[activePricingGroup.id] || null
    : null;
  const filteredGroupPricingItems = useMemo(() => {
    const items = activeGroupPricing?.items || [];
    const keyword = groupPricingSearch.trim().toLowerCase();
    if (!keyword) return items;
    return items.filter((item) => (
      String(item.model_name || '').toLowerCase().includes(keyword)
      || String(item.display_name || '').toLowerCase().includes(keyword)
      || String(item.category || '').toLowerCase().includes(keyword)
    ));
  }, [activeGroupPricing, groupPricingSearch]);

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-page-link/30 border-t-page-link" />
      </div>
    );
  }

  return (
    <div className="min-h-[calc(100dvh-72px)] w-full">
      {tokenDialog && (
        <TokenModal
          dialog={tokenDialog}
          form={tokenForm}
          onChange={setTokenForm}
          onSubmit={handleTokenSubmit}
          onClose={closeTokenDialog}
          onOpenAdvanced={loadAvailableModels}
          availableModels={availableModels}
          loadingModels={loadingModels}
          submitting={submittingToken}
          symbol={symbol}
          rate={rate}
          t={t}
        />
      )}

      <GroupPricingModal
        open={Boolean(activePricingGroup)}
        group={activePricingGroup}
        pricingData={activeGroupPricing}
        items={filteredGroupPricingItems}
        loading={loadingGroupPricingId === activePricingGroup?.id}
        search={groupPricingSearch}
        onSearchChange={setGroupPricingSearch}
        onClose={closeGroupPricing}
        symbol={symbol}
        rate={rate}
        cnyRate={cnyRate}
        t={t}
      />

      {newKey && (
        <div className="modal-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm">
          <div className="glass w-full max-w-lg rounded-2xl p-6">
            <div className="flex items-start gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-600">
                <ShieldCheck className="h-5 w-5" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-page">{t('tokens.newApiKey')}</h2>
                <p className="mt-1 text-sm leading-6 text-page-secondary">{t('tokens.keyWarning')}</p>
              </div>
            </div>
            <div className="mt-5 flex items-center gap-3 rounded-xl border border-page-divider bg-page-inset p-3">
              <code className="min-w-0 flex-1 break-all font-mono text-sm text-page-success select-all">{newKey}</code>
              <button
                type="button"
                onClick={() => handleCopy(newKey)}
                className="btn-primary inline-flex shrink-0 items-center gap-2 !px-4 !py-2"
              >
                <Copy className="h-4 w-4" />
                {copiedId === newKey ? t('tokens.copied') : t('tokens.copy')}
              </button>
            </div>
            <div className="mt-5 flex justify-end">
              <button type="button" onClick={() => setNewKey(null)} className="btn-secondary">
                {t('tokens.savedKey')}
              </button>
            </div>
          </div>
        </div>
      )}

      {deleteConfirm && (
        <div
          className="modal-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
          onClick={() => setDeleteConfirm(null)}
        >
          <div className="glass w-full max-w-sm rounded-2xl p-6" onClick={(event) => event.stopPropagation()}>
            <div className="flex items-start gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-red-500/10 text-red-600">
                <Trash2 className="h-5 w-5" />
              </div>
              <div>
                <h2 className="text-lg font-semibold text-page">{t('tokens.deleteToken')}</h2>
                <p className="mt-1 text-sm leading-6 text-page-secondary">
                  {t('tokens.deleteConfirm', { name: deleteConfirm.name })}
                </p>
              </div>
            </div>
            <div className="mt-6 flex justify-end gap-3">
              <button type="button" onClick={() => setDeleteConfirm(null)} className="btn-secondary">
                {t('tokens.cancel')}
              </button>
              <button
                type="button"
                onClick={handleDelete}
                className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-red-500"
              >
                <Trash2 className="h-4 w-4" />
                {t('tokens.delete')}
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="mx-auto max-w-6xl px-4 pt-6 sm:px-6 lg:px-8">
        <header className="rounded-xl border border-page-divider bg-page-card-bg shadow-sm">
          <div className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-2xl font-bold text-page">{t('nav.apiKeys')}</h1>
            <p className="mt-1 text-sm text-page-secondary">
              {t('tokens.subtitle', { defaultValue: '创建、复制和管理用于调用 API 的密钥。' })}
            </p>
          </div>
          <button type="button" onClick={openCreateDefault} className="btn-primary inline-flex items-center justify-center gap-2 !px-4 !py-2.5">
            <Plus className="h-4 w-4" />
            {t('tokens.newKey')}
          </button>
          </div>
        </header>
      </div>

      <main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8">
        {hasGroups && (
          <section className="overflow-hidden rounded-lg border border-page-divider bg-page-card-bg shadow-sm">
            <div className="border-b border-page-divider px-5 py-4">
              <h2 className="text-base font-bold text-page">{t('tokens.selectGroup')}</h2>
              <p className="mt-1 text-sm text-page-secondary">{t('tokens.selectGroupSubtitle')}</p>
            </div>

            <div className="space-y-6 px-5 py-5">
              {Object.entries(groupedByVendor).map(([vendor, groups]) => (
                <div key={vendor}>
                  <div className="mb-3 flex items-center gap-2">
                    <h3 className="text-base font-semibold text-page">{vendor}</h3>
                    <span className="rounded-full bg-page-surface px-2 py-0.5 text-[11px] text-page-muted">
                      {groups.length} {t('tokens.groupCount')}
                    </span>
                  </div>
                  <div className="space-y-2">
                    {groups.map((group) => (
                      <KeyGroupCard
                        key={group.id}
                        group={group}
                        parseTags={parseGroupTags}
                        onSelect={openCreateFromGroup}
                        onViewPricing={openGroupPricing}
                        symbol={symbol}
                        cnyRate={cnyRate}
                        t={t}
                      />
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        <section className="mt-5 overflow-hidden rounded-lg border border-page-divider bg-page-card-bg shadow-sm">
          <div className="flex items-center justify-between gap-3 border-b border-page-divider px-5 py-4">
            <div className="flex min-w-0 items-center gap-2">
              <KeyRound className="h-4 w-4 shrink-0 text-page-link" />
              <h2 className="truncate text-base font-bold text-page">{t('tokens.myKeys')}</h2>
              <span className="text-xs text-page-muted">{visibleTokens.length}</span>
            </div>
          </div>

          {visibleTokens.length === 0 ? (
            <div className="px-4 py-16 text-center">
              <div className="mx-auto flex h-11 w-11 items-center justify-center rounded-lg bg-page-surface text-page-muted">
                <KeyRound className="h-5 w-5" />
              </div>
              <p className="mt-4 text-sm font-semibold text-page">{t('tokens.noKeys')}</p>
              <p className="mt-1 text-xs leading-5 text-page-muted">{t('tokens.noKeysHint')}</p>
              <button type="button" onClick={openCreateDefault} className="btn-primary mt-5 inline-flex items-center gap-2 !px-4 !py-2 text-xs">
                <Plus className="h-4 w-4" />
                {t('tokens.newKey')}
              </button>
            </div>
          ) : (
            <div className="divide-y divide-page-divider">
              {visibleTokens.map((token) => (
                <TokenWorkbenchRow
                  key={token.id}
                  token={token}
                  expanded={Boolean(expandedTokens[token.id])}
                  tokenModelState={tokenModels[token.id]}
                  copied={copiedId === getTokenSecret(token)}
                  onCopy={() => handleCopy(getTokenSecret(token))}
                  onEdit={() => openEdit(token)}
                  onToggleModels={() => handleToggleSupportedModels(token.id)}
                  onToggle={() => handleToggle(token)}
                  onDelete={() => setDeleteConfirm(token)}
                  t={t}
                />
              ))}
            </div>
          )}
        </section>
      </main>
    </div>
  );
}

function TokenWorkbenchRow({
  token,
  expanded,
  tokenModelState,
  copied,
  onCopy,
  onEdit,
  onToggleModels,
  onToggle,
  onDelete,
  t,
}) {
  const enabled = Number(token.status) === 1;

  return (
    <div className="px-5 py-4">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div className="flex min-w-0 items-start gap-3">
          <span className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${enabled ? 'bg-emerald-500' : 'bg-page-muted'}`} />
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <p className="truncate text-sm font-semibold text-page">{token.name}</p>
              <span className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ${
                enabled ? 'bg-emerald-500/10 text-emerald-600' : 'bg-page-surface text-page-muted'
              }`}>
                {enabled ? t('tokens.enabled') : t('tokens.disabled')}
              </span>
            </div>
            <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-page-muted">
              <code className="font-mono">{getTokenPreview(token)}</code>
              {token.created_time && <span>{formatTokenDate(token.created_time)}</span>}
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2 lg:justify-end">
          <button
            type="button"
            onClick={onToggleModels}
            className="btn-secondary inline-flex items-center gap-1.5 !px-3 !py-1.5 text-xs"
          >
            <ListChecks className="h-3.5 w-3.5" />
            {expanded ? t('tokens.hideSupportedModels') : t('tokens.viewSupportedModels')}
          </button>
          <button
            type="button"
            onClick={onEdit}
            className="btn-secondary inline-flex items-center gap-1.5 !px-3 !py-1.5 text-xs"
          >
            <Pencil className="h-3.5 w-3.5" />
            {t('tokens.edit')}
          </button>
          <button
            type="button"
            onClick={onToggle}
            className={`btn-secondary inline-flex items-center gap-1.5 !px-3 !py-1.5 text-xs ${enabled ? 'text-amber-700 hover:bg-amber-500/10' : 'text-emerald-700 hover:bg-emerald-500/10'}`}
          >
            <KeyRound className="h-3.5 w-3.5" />
            {enabled ? t('tokens.disable') : t('tokens.enable')}
          </button>
          <button
            type="button"
            onClick={onDelete}
            className="btn-secondary inline-flex items-center gap-1.5 !px-3 !py-1.5 text-xs text-red-600 hover:bg-red-500/10"
          >
            <Trash2 className="h-3.5 w-3.5" />
            {t('tokens.delete')}
          </button>
          <button
            type="button"
            onClick={onCopy}
            disabled={!token.key}
            title={t('tokens.copy')}
            className="btn-secondary inline-flex items-center gap-1.5 !px-3 !py-1.5 text-xs"
          >
            <Copy className="h-3.5 w-3.5" />
            {copied ? t('tokens.copied') : t('tokens.copy')}
          </button>
        </div>
      </div>

      {expanded && (
        <div className="mt-4 rounded-xl border border-page-divider bg-page-surface/45 px-4 py-3">
          {tokenModelState?.loading ? (
            <div className="flex items-center gap-2 text-sm text-page-secondary">
              <div className="h-4 w-4 animate-spin rounded-full border-2 border-page-link/30 border-t-page-link" />
              {t('tokens.loadingSupportedModels')}
            </div>
          ) : tokenModelState?.error ? (
            <p className="text-sm text-page-danger">{t('tokens.loadSupportedModelsFailed')}</p>
          ) : (
            <>
              <div className="flex flex-wrap items-center gap-2">
                <p className="text-sm font-semibold text-page">
                  {t('tokens.supportedModels')} ({tokenModelState?.count || 0})
                </p>
                {tokenModelState?.restricted_by_models && (
                  <span className="rounded-full bg-page-link/10 px-2 py-0.5 text-[11px] text-page-link">
                    {t('tokens.restrictedByModels')}
                  </span>
                )}
                {tokenModelState?.restricted_by_providers && (
                  <span className="rounded-full bg-page-link/10 px-2 py-0.5 text-[11px] text-page-link">
                    {t('tokens.restrictedByProviders')}
                  </span>
                )}
              </div>
              {tokenModelState?.provider_names?.length > 0 && (
                <div className="mt-2 flex flex-wrap items-center gap-2">
                  <span className="text-xs text-page-muted">{t('tokens.supportedProviders')}</span>
                  {tokenModelState.provider_names.map((name) => (
                    <span key={name} className="rounded-full bg-page-inset px-2 py-0.5 text-[11px] text-page-secondary">
                      {name}
                    </span>
                  ))}
                </div>
              )}
              {tokenModelState?.models?.length > 0 ? (
                <div className="mt-3 flex flex-wrap gap-2">
                  {tokenModelState.models.map((modelName) => (
                    <code key={modelName} className="rounded-lg bg-page-inset px-2.5 py-1 font-mono text-[11px] text-page-secondary">
                      {modelName}
                    </code>
                  ))}
                </div>
              ) : (
                <p className="mt-3 text-sm text-page-muted">{t('tokens.noSupportedModels')}</p>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}

function TokenModal({
  dialog,
  form,
  onChange,
  onSubmit,
  onClose,
  onOpenAdvanced,
  availableModels,
  loadingModels,
  submitting,
  symbol,
  rate,
  t,
}) {
  const [modelInput, setModelInput] = useState('');
  const editing = Boolean(dialog.token);
  const setField = (field, value) => onChange((current) => ({ ...current, [field]: value }));
  const quotaAmount = form.remain_quota > 0
    ? Number(((form.remain_quota / Q) * rate).toFixed(2))
    : '';
  const setExpiration = (days) => setField(
    'expired_time',
    days ? timestampToLocalInput(Math.floor((Date.now() + days * 86400000) / 1000)) : '',
  );
  const addModel = () => {
    const model = modelInput.trim();
    if (!model || form.model_limits.includes(model)) return;
    if (!availableModels.includes(model)) {
      toast.error(t('tokens.invalidModel'));
      return;
    }
    setField('model_limits', [...form.model_limits, model]);
    setModelInput('');
  };

  return (
    <div className="modal-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4 backdrop-blur-[2px]" onClick={onClose}>
      <form
        onSubmit={onSubmit}
        onClick={(event) => event.stopPropagation()}
        className="flex max-h-[min(92vh,820px)] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-page-divider bg-page-bg shadow-2xl"
      >
        <div className="overflow-y-auto">
          <div className="px-8 pb-2 pt-7">
            <h2 className="text-xl font-semibold text-page">
              {editing ? t('tokens.editApiKey') : t('tokens.createApiKey')}
            </h2>
          </div>

          <div className="space-y-6 px-8 pb-8 pt-4">
            <div>
              <label className="mb-1.5 block text-sm font-medium text-page-label">{t('tokens.name')}</label>
              <input
                type="text"
                value={form.name}
                onChange={(event) => setField('name', event.target.value)}
                className="input"
                placeholder={t('tokens.namePlaceholder')}
                autoFocus
                required
              />
            </div>

            <details
              className="group/advanced rounded-xl border border-page-divider bg-page-surface/40"
              onToggle={(event) => event.currentTarget.open && onOpenAdvanced()}
            >
            <summary className="flex cursor-pointer list-none items-center gap-3 px-4 py-3 outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-page-link/50 [&::-webkit-details-marker]:hidden">
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-page">{t('tokens.advancedSettings')}</p>
                <p className="mt-0.5 text-xs text-page-muted">{t('tokens.advancedSettingsDesc')}</p>
              </div>
              <ChevronDown className="h-4 w-4 text-page-muted transition-transform group-open/advanced:rotate-180" />
            </summary>

              <div className="space-y-4 border-t border-page-divider px-4 pb-4 pt-4">
              {dialog.group && (
                <div className="rounded-lg border border-page-divider bg-page-inset px-3 py-2">
                  <p className="text-xs text-page-muted">{t('tokens.selectedGroup')}</p>
                  <p className="text-sm font-medium text-page">{dialog.group.name}</p>
                </div>
              )}

              <label className="flex items-center justify-between gap-3 rounded-xl border border-page-divider px-4 py-3">
                <span className="text-sm font-medium text-page">{t('tokens.unlimitedQuota')}</span>
                <input
                  type="checkbox"
                  checked={form.unlimited_quota}
                  onChange={(event) => setField('unlimited_quota', event.target.checked)}
                  className="h-4 w-4 accent-page-link"
                />
              </label>

              <div className="grid gap-4 md:grid-cols-2">
                <div>
                  <label className="mb-1.5 block text-sm font-medium text-page-label">{t('tokens.quotaLimit')}</label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    value={quotaAmount}
                    onChange={(event) => setField(
                      'remain_quota',
                      event.target.value === ''
                        ? 0
                        : Math.max(0, Math.round((Number(event.target.value) / rate) * Q)),
                    )}
                    className="input"
                    placeholder={t('tokens.quotaAmountPlaceholder', { symbol })}
                    disabled={form.unlimited_quota}
                  />
                  <div className="mt-2 flex flex-wrap gap-2">
                    {[1, 10, 50, 100].map((amount) => (
                      <button
                        key={amount}
                        type="button"
                        className="rounded-lg border border-page-divider px-2.5 py-1 text-xs text-page-secondary hover:bg-page-surface-hover disabled:opacity-40"
                        onClick={() => setField('remain_quota', Math.round((amount / rate) * Q))}
                        disabled={form.unlimited_quota}
                      >
                        {symbol}{amount}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="mb-1.5 block text-sm font-medium text-page-label">{t('tokens.expirationTime')}</label>
                  <DateTimePicker
                    value={form.expired_time}
                    onChange={(value) => setField('expired_time', value)}
                    placeholder={t('tokens.expirationTime')}
                    ariaLabel={t('tokens.expirationTime')}
                  />
                  <div className="mt-2 flex flex-wrap gap-2">
                    <button type="button" className="rounded-lg border border-page-divider px-2.5 py-1 text-xs text-page-secondary hover:bg-page-surface-hover" onClick={() => setExpiration(0)}>{t('tokens.neverExpires')}</button>
                    <button type="button" className="rounded-lg border border-page-divider px-2.5 py-1 text-xs text-page-secondary hover:bg-page-surface-hover" onClick={() => setExpiration(1)}>{t('tokens.oneDay')}</button>
                    <button type="button" className="rounded-lg border border-page-divider px-2.5 py-1 text-xs text-page-secondary hover:bg-page-surface-hover" onClick={() => setExpiration(30)}>{t('tokens.oneMonth')}</button>
                  </div>
                </div>
              </div>

              <div>
                <label className="mb-1.5 block text-sm font-medium text-page-label">{t('tokens.routePriority')}</label>
                <select value={form.subrouter_sort_mode} onChange={(event) => setField('subrouter_sort_mode', event.target.value)} className="input">
                  <option value="token_price_first">{t('tokens.tokenPriceFirst')}</option>
                  <option value="per_call_price_first">{t('tokens.perCallPriceFirst')}</option>
                </select>
              </div>

              <div>
                <label className="mb-1.5 block text-sm font-medium text-page-label">{t('tokens.modelAllowlist')}</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    list="token-model-options"
                    value={modelInput}
                    onChange={(event) => setModelInput(event.target.value)}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter') {
                        event.preventDefault();
                        addModel();
                      }
                    }}
                    className="input"
                    placeholder={loadingModels ? t('tokens.loadingSupportedModels') : t('tokens.modelAllowlistPlaceholder')}
                    disabled={loadingModels}
                  />
                  <datalist id="token-model-options">
                    {availableModels.map((model) => <option key={model} value={model} />)}
                  </datalist>
                  <button type="button" className="btn-secondary shrink-0" onClick={addModel} disabled={loadingModels}>{t('tokens.addModel')}</button>
                </div>
                {form.model_limits.length > 0 ? (
                  <div className="mt-3 flex flex-wrap gap-2">
                    {form.model_limits.map((model) => (
                      <button
                        key={model}
                        type="button"
                        onClick={() => setField('model_limits', form.model_limits.filter((item) => item !== model))}
                        className="rounded-lg bg-page-inset px-2.5 py-1 font-mono text-xs text-page-secondary hover:text-page-danger"
                        title={t('tokens.removeModel')}
                      >
                        {model} ×
                      </button>
                    ))}
                  </div>
                ) : (
                  <p className="mt-1 text-xs text-page-muted">{t('tokens.noModelLimit')}</p>
                )}
              </div>

              <div>
                <label className="mb-1.5 block text-sm font-medium text-page-label">{t('tokens.ipAllowlist')}</label>
                <textarea
                  value={form.allow_ips}
                  onChange={(event) => setField('allow_ips', event.target.value)}
                  className="input min-h-24 resize-y"
                  placeholder={t('tokens.ipAllowlistPlaceholder')}
                />
              </div>
            </div>
            </details>
          </div>
        </div>

        <div className="flex justify-end gap-3 border-t border-page-divider bg-page-bg px-8 py-5">
          <button type="button" onClick={onClose} className="btn-secondary">{t('tokens.cancel')}</button>
          <button type="submit" disabled={submitting} className="btn-primary">
            {submitting ? t(editing ? 'tokens.saving' : 'tokens.creating') : t(editing ? 'tokens.save' : 'tokens.create')}
          </button>
        </div>
      </form>
    </div>
  );
}

function KeyGroupCard({ group, parseTags, onSelect, onViewPricing, symbol, cnyRate, t }) {
  const tags = parseTags(group.tags);
  const unavailable = Boolean(group.is_unavailable);

  return (
    <div className={`rounded-xl border border-page-divider bg-page-card-bg p-4 ${
      unavailable ? 'opacity-70' : 'transition-colors hover:border-page-link/40'
    }`}>
      <div className="flex items-start gap-3">
        <div className="min-w-0 flex-1">
          <div className="flex flex-wrap items-center gap-2">
            <p className="text-sm font-semibold text-page">{group.name}</p>
            {group.is_recommended && (
              <span className="rounded-full bg-amber-500/10 px-2 py-0.5 text-[10px] font-semibold text-amber-700">{t('tokens.recommended')}</span>
            )}
            {unavailable && (
              <span className="rounded-full bg-red-500/10 px-2 py-0.5 text-[10px] font-semibold text-red-600">{t('tokens.unavailable')}</span>
            )}
          </div>
          <div className="mt-1.5 flex flex-wrap items-center gap-2">
            {group.rmb_per_usd > 0 && (
              <span className="text-xs font-medium text-page">{formatCnyPerUsdRate(group.rmb_per_usd, symbol, cnyRate)} {t('tokens.perUsd')}</span>
            )}
            {group.discount_label && <span className="text-[11px] font-semibold text-page-success">{group.discount_label}</span>}
            {tags.map((tag) => <span key={tag} className="rounded bg-page-surface px-1.5 py-0.5 text-[10px] text-page-secondary">{tag}</span>)}
          </div>
          {group.description && <p className="mt-1 text-xs text-page-muted">{group.description}</p>}
        </div>
        <div className="flex shrink-0 flex-col items-end gap-2">
          <button type="button" onClick={() => onViewPricing(group)} className="btn-secondary !px-3 !py-1.5 text-xs">
            {t('tokens.viewGroupPricing')}
          </button>
          {!unavailable && (
            <button type="button" onClick={() => onSelect(group)} className="text-xs font-semibold text-page-link hover:underline">
              {t('tokens.create')} →
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

function GroupPricingModal({
  open,
  group,
  pricingData,
  items,
  loading,
  search,
  onSearchChange,
  onClose,
  symbol,
  rate,
  cnyRate,
  t,
}) {
  if (!open || !group) return null;
  const displayGroup = pricingData?.group || group;
  const summary = pricingData?.summary;

  return (
    <div className="modal-overlay fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm" onClick={onClose}>
      <div className="glass flex max-h-[88vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl" onClick={(event) => event.stopPropagation()}>
        <div className="border-b border-page-divider px-6 py-5">
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-xl font-semibold text-page">{displayGroup.name} · {t('tokens.groupPricingTitle')}</h2>
              <p className="mt-1 max-w-3xl text-sm text-page-secondary">{t('tokens.groupPricingSubtitle')}</p>
            </div>
            <button type="button" onClick={onClose} className="btn-secondary !px-3 !py-1.5 text-xs">{t('tokens.cancel')}</button>
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-2 text-xs text-page-secondary">
            {displayGroup.discount_label && <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-emerald-700">{displayGroup.discount_label}</span>}
            {displayGroup.rmb_per_usd > 0 && <span className="rounded-full bg-page-surface px-2.5 py-1">{formatCnyPerUsdRate(displayGroup.rmb_per_usd, symbol, cnyRate)} {t('tokens.perUsd')}</span>}
            {summary && <span className="rounded-full bg-page-surface px-2.5 py-1">{t('tokens.groupPricingAvailableModels')}: {summary.model_count}</span>}
          </div>
        </div>
        <div className="flex flex-col gap-3 border-b border-page-divider bg-page-surface/40 px-6 py-4 lg:flex-row lg:items-center lg:justify-between">
          <p className="text-sm text-page-secondary">{t('tokens.groupPricingNotice')}</p>
          <input
            type="search"
            value={search}
            onChange={(event) => onSearchChange(event.target.value)}
            className="input lg:max-w-xs"
            placeholder={t('tokens.groupPricingSearchPlaceholder')}
          />
        </div>
        <div className="max-h-[58vh] overflow-y-auto px-6 py-5">
          {loading ? (
            <div className="flex items-center gap-2 text-sm text-page-secondary">
              <div className="h-4 w-4 animate-spin rounded-full border-2 border-page-link/30 border-t-page-link" />
              {t('tokens.groupPricingLoading')}
            </div>
          ) : items.length === 0 ? (
            <p className="text-sm text-page-secondary">{pricingData ? t('tokens.groupPricingNoMatch') : t('tokens.groupPricingNoData')}</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[760px] text-sm">
                <thead>
                  <tr className="border-b border-page-divider text-left text-page-secondary">
                    <th className="px-3 py-3 font-medium">{t('pricing.model')}</th>
                    <th className="px-3 py-3 text-right font-medium">{t('tokens.groupPricingReferencePrice')}</th>
                    <th className="px-3 py-3 text-right font-medium">{t('pricing.outputPrice')}</th>
                    <th className="px-3 py-3 text-center font-medium">{t('tokens.groupPricingLines')}</th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((item) => (
                    <tr key={`${item.model_name}:${item.billing_type}`} className="border-b border-page-divider last:border-0">
                      <td className="px-3 py-3">
                        <div className="font-medium text-page">{item.display_name || item.model_name}</div>
                        {item.display_name && item.display_name !== item.model_name && <div className="mt-1 font-mono text-xs text-page-muted">{item.model_name}</div>}
                      </td>
                      <td className="px-3 py-3 text-right font-mono text-xs text-page-label">
                        {item.status !== 'healthy'
                          ? t('pricing.unknown')
                          : item.billing_type === 'per_call'
                            ? formatGroupPriceRange(item.fixed_price_min, item.fixed_price_max, symbol, rate, true, t)
                            : formatGroupPriceRange(item.input_price_min, item.input_price_max, symbol, rate, false, t)}
                      </td>
                      <td className="px-3 py-3 text-right font-mono text-xs text-page-label">
                        {item.status !== 'healthy' || item.billing_type === 'per_call'
                          ? '-'
                          : formatGroupPriceRange(item.output_price_min, item.output_price_max, symbol, rate, false, t)}
                      </td>
                      <td className="px-3 py-3 text-center text-xs text-page-secondary">{formatRouteCount(item.route_count, item.has_range, t)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function formatCnyPerUsdRate(value, symbol, cnyRate) {
  const amount = Number(value) * Number(cnyRate || 1);
  if (!Number.isFinite(amount) || amount <= 0) return '';
  return `${symbol}${amount.toFixed(amount >= 10 ? 2 : 4)}`;
}

function formatGroupPriceRange(min, max, symbol, rate, perCall, t) {
  if (min == null && max == null) return '-';
  const low = Number(min ?? max ?? 0);
  const high = Number(max ?? min ?? 0);
  const factor = perCall ? rate : rate * 1000;
  const suffix = perCall ? `/${t('pricing.perCallUnit')}` : '';
  const lowText = `${symbol}${(low * factor).toFixed(4)}`;
  const highText = `${symbol}${(high * factor).toFixed(4)}`;
  return Math.abs(low - high) <= 1e-9
    ? `${lowText}${suffix}`
    : `${lowText} - ${highText}${suffix}`;
}

function formatRouteCount(routeCount, hasRange, t) {
  if (!routeCount) return t('pricing.unknown');
  if (routeCount === 1) return `1 ${t('tokens.groupPricingLineUnitSingle')}`;
  if (!hasRange) return `${routeCount} ${t('tokens.groupPricingLineUnit')} · ${t('tokens.groupPricingSamePrice')}`;
  return `${routeCount} ${t('tokens.groupPricingLineUnit')}`;
}
