export const DOCS_OVERVIEW_SEO_COPY = {
  en: {
    title: 'What Is API-Route? A Multi-Model AI API and OpenRouter Alternative',
    description: 'Explore API-Route, an OpenAI-compatible multi-model API with multi-provider routing, automatic failover, transparent pricing, and a practical OpenRouter alternative for developers and teams.',
  },
  zh: {
    title: '什么是 API-Route？多模型 AI API 与 OpenRouter 替代方案',
    description: '了解 API-Route 如何通过 OpenAI 兼容的多模型 API 提供多供应商路由、自动故障切换和透明价格，以及它与官方 API 和 OpenRouter 的区别。',
  },
  ja: {
    title: 'API-Routeとは？マルチモデルAI APIとOpenRouterの代替候補',
    description: 'OpenAI 互換マルチモデル API、複数プロバイダーのルーティング、自動フェイルオーバー、明確な料金を提供する API-Route と、公式 API・OpenRouter との違いを紹介します。',
  },
  ko: {
    title: 'API-Route란? 멀티 모델 AI API와 OpenRouter 대안',
    description: 'OpenAI 호환 멀티 모델 API, 다중 공급자 라우팅, 자동 장애 전환, 투명한 가격을 제공하는 API-Route와 공식 API 및 OpenRouter의 차이를 확인하세요.',
  },
};

export const DOCS_CODEX_CUSTOM_PROVIDER_SEO_COPY = {
  en: {
    title: 'Use API-Route in Codex App and Codex CLI',
    description: 'Configure API-Route as a Codex custom provider with CC Switch on Windows or macOS, or replace config.toml and auth.json for Codex CLI on Linux.',
    keywords: 'Codex custom provider,Codex App custom API,Codex CLI config.toml,CC Switch Codex,API-Route Codex,Codex Linux configuration',
    questions: [
      ['How do I use API-Route in the Codex App?', 'On Windows or macOS, choose an API key, available model, and route in API Access, then import API-Route into Codex with CC Switch and activate the imported provider.'],
      ['How do I configure API-Route for Codex CLI on Linux?', 'Generate the Codex manual configuration in API Access, replace ~/.codex/config.toml with its config section, and save the generated API key object as ~/.codex/auth.json.'],
      ['Which API-Route endpoint and model should Codex use?', 'Use the endpoint and exact model ID generated by API Access for the selected active key and route. Do not guess or hard-code values from an old screenshot.'],
    ],
    snapshotSections: [
      { title: 'Codex App on Windows and macOS', body: 'The recommended setup uses CC Switch to import the selected API-Route key, model, and endpoint into Codex, then activates the api-route provider.' },
      { title: 'Codex CLI on Linux', body: 'The manual setup replaces ~/.codex/config.toml with the generated provider configuration and stores the generated API key object in ~/.codex/auth.json.' },
    ],
  },
  zh: {
    title: 'Codex App 与 Codex CLI 接入 API-Route 教程',
    description: '在 Windows 或 macOS 上使用 CC Switch 将 API-Route 一键导入 Codex App，或在 Linux 上替换 config.toml 和 auth.json 配置 Codex CLI。',
    keywords: 'Codex 自定义供应商,Codex App 自定义 API,Codex CLI config.toml,CC Switch Codex,API-Route Codex,Codex Linux 配置',
    questions: [
      ['如何在 Codex App 中使用 API-Route？', '在 Windows 或 macOS 的 API 接入页面选择 API Key、可用模型和调用节点，再通过 CC Switch 导入 Codex，并启用导入的 api-route 供应商。'],
      ['Linux 如何配置 Codex CLI 使用 API-Route？', '在 API 接入页面生成 Codex 手动配置，用其中的配置段完整替换 ~/.codex/config.toml，并把生成的 API Key JSON 保存为 ~/.codex/auth.json。'],
      ['Codex 应该使用哪个调用地址和模型？', '应使用 API 接入页面根据当前已启用密钥和节点生成的调用地址与完整模型 ID，不要照抄旧截图或自行猜测。'],
    ],
    snapshotSections: [
      { title: 'Windows 与 macOS：Codex App', body: '推荐通过 CC Switch 把选定的 API-Route 密钥、模型和调用节点导入 Codex，再启用 api-route 供应商。' },
      { title: 'Linux：Codex CLI', body: '手动配置时，用生成的供应商配置替换 ~/.codex/config.toml，并将生成的 API Key JSON 保存到 ~/.codex/auth.json。' },
    ],
  },
  ja: {
    title: 'Codex App・Codex CLI で API-Route を使う方法',
    description: 'Windows・macOS では CC Switch で API-Route を Codex App に取り込み、Linux では config.toml と auth.json を置き換えて Codex CLI を設定します。',
    keywords: 'Codex カスタムプロバイダー,Codex App カスタム API,Codex CLI config.toml,CC Switch Codex,API-Route Codex,Codex Linux 設定',
    questions: [
      ['Codex App で API-Route を使うには？', 'Windows または macOS の API 連携画面で API キー、利用可能なモデル、接続先を選び、CC Switch で Codex に取り込んで api-route プロバイダーを有効にします。'],
      ['Linux の Codex CLI に API-Route を設定するには？', 'API 連携で Codex の手動設定を生成し、設定部分で ~/.codex/config.toml を置き換え、API キーの JSON を ~/.codex/auth.json に保存します。'],
      ['Codex ではどの接続先とモデルを使いますか？', '有効なキーと接続先に基づいて API 連携画面が生成した URL と正確なモデル ID を使います。古い画面例から推測しないでください。'],
    ],
    snapshotSections: [
      { title: 'Windows・macOS の Codex App', body: 'CC Switch で選択した API-Route のキー、モデル、接続先を Codex に取り込み、api-route プロバイダーを有効にする方法を推奨します。' },
      { title: 'Linux の Codex CLI', body: '生成されたプロバイダー設定で ~/.codex/config.toml を置き換え、API キーの JSON を ~/.codex/auth.json に保存します。' },
    ],
  },
  ko: {
    title: 'Codex App과 Codex CLI에서 API-Route 사용하는 방법',
    description: 'Windows와 macOS에서는 CC Switch로 API-Route를 Codex App에 가져오고, Linux에서는 config.toml과 auth.json을 교체해 Codex CLI를 설정합니다.',
    keywords: 'Codex 사용자 지정 공급자,Codex App 사용자 지정 API,Codex CLI config.toml,CC Switch Codex,API-Route Codex,Codex Linux 설정',
    questions: [
      ['Codex App에서 API-Route를 사용하려면 어떻게 하나요?', 'Windows 또는 macOS의 API 연결 화면에서 API 키, 사용 가능한 모델, 엔드포인트를 선택한 뒤 CC Switch로 Codex에 가져오고 api-route 공급자를 활성화합니다.'],
      ['Linux Codex CLI에 API-Route를 설정하려면 어떻게 하나요?', 'API 연결에서 Codex 수동 설정을 생성하고 설정 섹션으로 ~/.codex/config.toml을 교체한 뒤 API 키 JSON을 ~/.codex/auth.json에 저장합니다.'],
      ['Codex에서 어떤 엔드포인트와 모델을 사용해야 하나요?', '활성 키와 엔드포인트를 기준으로 API 연결 화면이 생성한 URL과 정확한 모델 ID를 사용하세요. 오래된 화면을 복사하거나 값을 추측하지 마세요.'],
    ],
    snapshotSections: [
      { title: 'Windows 및 macOS의 Codex App', body: 'CC Switch로 선택한 API-Route 키, 모델, 엔드포인트를 Codex에 가져온 뒤 api-route 공급자를 활성화하는 방식을 권장합니다.' },
      { title: 'Linux의 Codex CLI', body: '생성된 공급자 설정으로 ~/.codex/config.toml을 교체하고 API 키 JSON을 ~/.codex/auth.json에 저장합니다.' },
    ],
  },
};

export const DOCS_NAVIGATION_COPY = {
  en: {
    title: 'Documentation',
    overview: 'Product overview',
    quickstart: 'Quickstart',
    codexCustomProvider: 'Codex Custom Provider',
    onThisPage: 'On this page',
    selectLabel: 'Choose a documentation page',
  },
  zh: {
    title: '文档',
    overview: '产品概览',
    quickstart: '快速开始',
    codexCustomProvider: 'Codex 自定义供应商',
    onThisPage: '本页目录',
    selectLabel: '选择文档页面',
  },
  ja: {
    title: 'ドキュメント',
    overview: '製品概要',
    quickstart: 'クイックスタート',
    codexCustomProvider: 'Codex カスタムプロバイダー',
    onThisPage: 'このページの目次',
    selectLabel: 'ドキュメントページを選択',
  },
  ko: {
    title: '문서',
    overview: '제품 개요',
    quickstart: '빠른 시작',
    codexCustomProvider: 'Codex 사용자 지정 공급자',
    onThisPage: '이 페이지의 목차',
    selectLabel: '문서 페이지 선택',
  },
};
