import { DOCS_NAVIGATION_COPY, DOCS_OVERVIEW_SEO_COPY } from './docsSeoCopy.js';

export const DOCS_COPY = {
  en: {
    navigation: DOCS_NAVIGATION_COPY.en,
    overview: {
      eyebrow: 'Product overview',
      title: 'What is API-Route?',
      description: 'API-Route is an OpenAI-compatible multi-model AI API that brings model access, routing, pricing, balance, and request logs into one account.',
      seoTitle: DOCS_OVERVIEW_SEO_COPY.en.title,
      seoDescription: DOCS_OVERVIEW_SEO_COPY.en.description,
      directory: [
        ['what-is', 'What is API-Route'],
        ['how-it-works', 'How API-Route works'],
        ['routing-failover', 'Routing and failover'],
        ['pricing-cost', 'Pricing and cost'],
        ['alternatives', 'API-Route and alternatives'],
        ['start', 'Get started'],
      ],
      whatIs: {
        kicker: 'What is API-Route',
        title: 'What is API-Route',
        positionTitle: 'Product position',
        paragraphs: [
          'API-Route is an OpenAI-compatible multi-model AI API. It lets you call supported models through one Base URL and API key instead of maintaining a separate connection for every provider.',
          'The same account brings together current model pricing, account balance, plans, and request logs.',
        ],
        points: [
          'One Base URL and API key for supported models',
          'Unified model pricing and availability',
          'One place for balance and request records',
        ],
        audienceTitle: 'Users, models, and applications',
        audienceBody: 'API-Route is designed for AI application development, SaaS integration, and teams that need a unified way to call multiple models.',
        audienceItems: [
          ['Models', 'Supported models can change; use the Pricing page as the current source of truth instead of relying on a fixed list here.'],
          ['Tools', 'Current integration guidance covers Codex, Claude Code, LibreChat, VS Code, and other tools listed on the Apps page.'],
        ],
        links: [
          ['/pricing', 'View models and pricing'],
          ['/apps', 'Explore supported applications'],
          ['/docs/quickstart', 'View the Quickstart'],
        ],
      },
      workflow: {
        kicker: 'How API-Route works',
        title: 'How API-Route works',
        stepsTitle: 'Four-step workflow',
        steps: [
          ['Register an account', 'Create the account that owns the balance and API keys. You can register or sign in with a Google, X, or GitHub account.'],
          ['Add balance or buy a plan', 'Use the payment options currently shown on the Top Up page, then choose pay-as-you-go balance or an available plan.'],
          ['Create an API key', 'Create and securely save an enabled key from the API Keys page.'],
          ['Choose a model and call it', 'Use an exact model ID currently available to the key and send a request through the configured endpoint.'],
        ],
        keySettingsTitle: 'API key controls',
        keySettingsBody: 'Each API key can be configured separately, so applications and environments do not have to share the same limits or access rules.',
        keySettingsItems: [
          ['Quota and expiration', 'Use an unlimited key or set a fixed quota, then choose a specific expiration time or no expiration.'],
          ['Routing priority', 'Choose whether the key prioritizes token-priced routes or per-call-priced routes. Available routes still depend on the selected model and current backend status.'],
          ['Model allowlist', 'Restrict the key to selected models currently listed by the site. Leaving the list empty adds no model restriction beyond the key group and current listing status.'],
          ['IP allowlist', 'Allow one or more IP addresses or CIDR ranges. Leaving the list empty adds no IP restriction.'],
          ['Key groups and supported models', 'When key groups are available, create a key for a group, review its pricing, and inspect the models the key can currently use.'],
          ['Key lifecycle', 'Edit, enable, disable, or delete each key independently. A new secret is displayed once and should be stored securely.'],
        ],
        keySettingsLinks: [['/tokens', 'Manage API keys']],
        interfaceTitle: 'One interface',
        interfaceBody: 'The connection stays simple: the Base URL identifies the endpoint, the API key authorizes the request, and the model ID selects the model. Balance and request logs remain under the same account.',
        interfaceItems: [
          ['Base URL', 'The OpenAI-compatible endpoint used by supported clients and SDKs.'],
          ['API key', 'The credential created in your account for authenticated API requests.'],
          ['Model ID', 'The exact current model identifier selected for a request.'],
          ['Account and logs', 'A unified place to review balance, usage, and request records.'],
        ],
        link: 'Continue to the Quickstart',
      },
      routing: {
        kicker: 'Routing and failover',
        title: 'Multi-route routing and failover',
        multiRouteTitle: 'Multi-route design',
        multiRouteBody: 'The same model can have one or more available route nodes. On the Pricing page, “1 route”, “2 routes”, or “3 routes” shows the number of routes currently available for that model.',
        multiRouteItems: [
          'Multiple routes can reduce dependence on a single upstream node.',
          'Not every model has more than one route.',
          'The current route count is always the value shown on the Pricing page.',
        ],
        failoverTitle: 'Failover and its limits',
        failoverBody: 'This multi-provider AI API routing design supports automatic API failover: when the current route errors, times out, or is temporarily unavailable, the system can retry or switch to another available route according to its routing policy.',
        failoverItems: [
          'An LLM API fallback can reduce the impact of a single-node failure.',
          'Multiple routes make the AI gateway more fault-tolerant, but do not guarantee zero failures.',
          'Actual route availability varies by model and time.',
        ],
        flow: ['User request', 'Select an available route', 'Retry or switch on error'],
      },
      pricing: {
        kicker: 'Pricing and cost',
        title: 'Pricing and cost',
        billingTitle: 'How API usage is billed',
        billingBody: 'Billing units depend on the selected model. Actual charges are determined by the current Pricing page, account records, and request logs.',
        billingItems: [
          ['Input tokens', 'Text or context sent to a token-priced model.'],
          ['Output tokens', 'Text generated by the model.'],
          ['Cache fees', 'Supported models may price cache reads and cache creation separately.'],
          ['Per-call and media pricing', 'Images, audio, video, and other media models may charge by call, duration, resolution, or another listed specification.'],
          ['Balance and plans', 'Usage can consume account balance or an available plan according to its terms and limits.'],
        ],
        links: [
          ['/pricing', 'Compare model pricing'],
          ['/packages', 'View plans'],
        ],
        lowerTitle: 'Why prices can be below official reference pricing',
        lowerBody: 'Affordable AI API pricing can come from combining several available upstream suppliers and route nodes. Different suppliers may use different bulk purchasing, partner settlement, and cost structures.',
        lowerItems: [
          ['Operating cost', 'Aggregated request volume, shared infrastructure, and automated routing can lower the cost per call.'],
          ['Official comparison', 'Official API pricing is the model provider’s published retail price and is used as a reference for comparison.'],
          ['Route differences', 'Routes can differ in price, latency, limits, context capabilities, and availability. Lower AI API pricing does not mean every route has exactly the same characteristics as an official direct connection.'],
        ],
      },
      alternatives: {
        kicker: 'Service comparison',
        title: 'API-Route and other options',
        body: 'Each option has a valid use case. The comparisons below focus on account and integration differences without ranking provider quality.',
        officialApis: {
          title: 'API-Route and official model APIs',
          body: 'Official APIs remain the direct service from OpenAI, Anthropic, Google, and other providers. API-Route focuses on reducing the operational work of using several providers through one account.',
          headers: ['Area', 'API-Route', 'Official model APIs'],
          rows: [
            ['Provider accounts', 'One API-Route account', 'A separate account with each selected provider'],
            ['Base URL and API keys', 'One compatible Base URL and API key workflow', 'Provider-specific endpoints and credentials'],
            ['Model pricing', 'Compared on one Pricing page', 'Reviewed on each provider’s pricing page'],
            ['Balance and request logs', 'Managed in one account', 'Managed in each provider console'],
            ['Client configuration', 'Reuse one compatible connection and change model IDs', 'Configure each provider integration separately'],
          ],
        },
        openRouter: {
          title: 'Is API-Route an OpenRouter Alternative?',
          body: 'API-Route and OpenRouter both serve users who want unified access to multiple models. OpenRouter also provides a multi-model interface, OpenAI SDK compatibility, and provider routing, so those capabilities are not unique to API-Route.',
          headers: ['Area', 'API-Route', 'OpenRouter'],
          rows: [
            ['Unified multi-model API', 'Uses the models currently listed by API-Route', 'Provides its own model catalog and provider routing'],
            ['OpenAI API compatibility', 'Provides an OpenAI-compatible API and Base URL', 'Supports OpenAI SDK-compatible usage'],
            ['Payment options', 'Shows the methods currently available on the Top Up page', 'Check OpenRouter’s current billing page for supported methods and regions'],
            ['Plans and balance', 'Supports account balance and available usage plans', 'Compare OpenRouter’s current credit and billing terms'],
            ['Client access', 'Provides configuration flows for supported tools such as Codex and Claude Code', 'Confirm custom endpoint support using current client and OpenRouter guidance'],
            ['Localization and support', 'Offers English, Simplified Chinese, Japanese, and Korean pages plus the site’s displayed support channel', 'Review OpenRouter’s current languages and official support channels'],
          ],
          conclusion: 'The two services have a similar direction. Choose based on payment methods, plan and balance preferences, client configuration, localized support, and the specific models you need.',
        },
      },
      start: {
        kicker: 'Get started',
        title: 'Get started',
        modesTitle: 'Choose a usage mode',
        modes: [
          ['AI Chat', 'Use the site’s web chat with models currently available for that product.'],
          ['API integration', 'Connect an application, SDK, script, or supported client through the API.'],
          ['Independent platform', 'Use the existing independent-site option when you need a separate platform for your own users.'],
        ],
        nextTitle: 'Next step',
        body: 'Open the detailed setup guide, compare current model costs, or create an account.',
        actions: [
          ['/docs/quickstart', 'View the Quickstart', 'primary'],
          ['/pricing', 'Compare model pricing', 'secondary'],
          ['/register', 'Create an account', 'secondary'],
        ],
      },
    },
  },
  zh: {
    navigation: DOCS_NAVIGATION_COPY.zh,
    overview: {
      eyebrow: '产品概览',
      title: '什么是 API-Route？',
      description: 'API-Route 是一个兼容 OpenAI 格式的多模型 AI API，在同一账户中提供模型调用、路由、价格、余额和调用记录。',
      seoTitle: DOCS_OVERVIEW_SEO_COPY.zh.title,
      seoDescription: DOCS_OVERVIEW_SEO_COPY.zh.description,
      directory: [
        ['what-is', '什么是 API-Route'],
        ['how-it-works', 'API-Route 如何工作'],
        ['routing-failover', '多路由与故障切换'],
        ['pricing-cost', '价格与成本'],
        ['alternatives', 'API-Route 与其他方案'],
        ['start', '开始使用'],
      ],
      whatIs: {
        kicker: '什么是 API-Route',
        title: '什么是 API-Route',
        positionTitle: '产品定位',
        paragraphs: [
          'API-Route 是一个 OpenAI-compatible 多模型 AI API。开发者可以使用同一个 Base URL 和 API Key 调用已支持的模型，不必分别维护每个供应商的接入配置。',
          '模型价格、账户余额、套餐和调用记录都集中在同一个账户中。',
        ],
        points: [
          '一个 Base URL 和 API Key 调用已支持模型',
          '统一查看模型价格和可用状态',
          '集中管理余额和调用记录',
        ],
        audienceTitle: '适用用户、模型与应用',
        audienceBody: 'API-Route 适合 AI 应用开发、SaaS 产品集成，以及需要统一调用多个模型的开发者和团队。',
        audienceItems: [
          ['模型', '具体支持的模型可能变化，请以定价页实时展示为准，不在概览中维护一份容易过期的长清单。'],
          ['工具', '当前接入说明覆盖 Codex、Claude Code、LibreChat、VS Code，以及应用页列出的其他工具。'],
        ],
        links: [
          ['/pricing', '查看模型与价格'],
          ['/apps', '查看应用生态'],
          ['/docs/quickstart', '查看快速开始'],
        ],
      },
      workflow: {
        kicker: 'API-Route 如何工作',
        title: 'API-Route 如何工作',
        stepsTitle: '四步使用流程',
        steps: [
          ['注册账户', '创建用于管理余额和 API Key 的账户，支持使用 Google、X 或 GitHub 账号注册和登录。'],
          ['充值余额或购买套餐', '使用充值页当前提供的支付方式，再选择按余额用量扣费或购买可用套餐。'],
          ['创建 API Key', '在 API 密钥页面创建并安全保存一个已启用的密钥。'],
          ['选择模型并发起调用', '使用密钥当前可调用的完整模型 ID，通过配置好的接口发送请求。'],
        ],
        keySettingsTitle: 'API Key 管理与访问控制',
        keySettingsBody: '每个 API Key 都可以独立配置，方便为不同应用和环境设置各自的额度与访问规则。',
        keySettingsItems: [
          ['额度与有效期', '可设为不限额或指定额度上限，并选择具体过期时间或永不过期。'],
          ['路由优先级', '可选择按 Token 价格优先或按次调用价格优先；实际可用路由仍取决于所选模型和后端当前状态。'],
          ['模型白名单', '可限制密钥只能调用当前已上架的指定模型；留空时不额外限制，但仍受密钥分组和后台上下架状态约束。'],
          ['IP 白名单', '可填写一个或多个 IP 地址或 CIDR 网段；留空时不限制来源 IP。'],
          ['密钥分组与可用模型', '站点提供密钥分组时，可按分组创建密钥、查看分组价格，并检查该密钥当前可调用的模型。'],
          ['密钥生命周期', '可分别编辑、启用、停用或删除密钥。新密钥仅显示一次，创建后应立即安全保存。'],
        ],
        keySettingsLinks: [['/tokens', '管理 API 密钥']],
        interfaceTitle: '统一接口方式',
        interfaceBody: 'Base URL 用于确定接口地址，API Key 用于请求鉴权，模型 ID 用于选择模型；余额、用量和调用日志则统一归入同一个账户。',
        interfaceItems: [
          ['Base URL', '供支持 OpenAI 兼容接口的客户端和 SDK 使用的接口地址。'],
          ['API Key', '在账户中创建、用于 API 请求鉴权的凭证。'],
          ['模型 ID', '每次请求中用于选择模型的当前完整标识。'],
          ['账户与调用日志', '统一查看余额、用量和调用记录。'],
        ],
        link: '继续查看快速开始',
      },
      routing: {
        kicker: '多路由与故障切换',
        title: '多路由与故障切换',
        multiRouteTitle: '多路由机制',
        multiRouteBody: '同一个模型可以配置一个或多个可用路由节点。价格页显示的“1 route”“2 routes”“3 routes”，代表该模型当前可用的路由数量。',
        multiRouteItems: [
          '多个路由可以降低对单一上游节点的依赖。',
          '并非所有模型都有多个路由。',
          '具体路由数量以价格页实时展示为准。',
        ],
        failoverTitle: '故障切换与能力边界',
        failoverBody: '当当前路由请求异常、超时或暂时不可用时，系统可以按照既定路由策略重试，或切换到其他可用路由。',
        failoverItems: [
          '多路由可以降低单一节点故障造成的影响。',
          '故障切换不代表绝对零故障，也不承诺所有模型始终存在备用路由。',
          '实际可用路由会随模型和时间变化。',
        ],
        flow: ['用户请求', '选择可用路由', '异常时重试或切换备用节点'],
      },
      pricing: {
        kicker: '价格与成本',
        title: '价格与成本',
        billingTitle: 'API 如何计费',
        billingBody: '不同模型使用不同计价单位，实际扣费以价格页、账户记录和调用日志为准。',
        billingItems: [
          ['输入 Token', '发送给按 Token 计费模型的文字或上下文。'],
          ['输出 Token', '模型生成的文字内容。'],
          ['缓存费用', '支持缓存的模型可能分别计算缓存读取和缓存创建费用。'],
          ['按次或媒体规格计费', '图片、音频、视频等模型可能按照调用、时长、分辨率或表格列出的其他规格计费。'],
          ['余额与套餐', '调用可以消耗账户余额，也可以按可用套餐的条款和额度扣除。'],
        ],
        links: [
          ['/pricing', '比较模型价格'],
          ['/packages', '查看套餐'],
        ],
        lowerTitle: '为什么价格可以低于官方参考价',
        lowerBody: 'API-Route 接入多个可用上游供应渠道和路由节点。不同渠道可能采用不同的批量采购、合作结算和成本结构。',
        lowerItems: [
          ['单位成本', '聚合调用量、共享基础设施和自动化路由可以降低单位调用成本。'],
          ['官方参考价', '官方价格是模型厂商公开零售价，用于价格比较和成本参考。'],
          ['路由差异', '不同路由在价格、延迟、限额、上下文能力和可用性方面可能存在差异。价格较低不代表所有路由都与官方直连具有完全相同的特性。'],
        ],
      },
      alternatives: {
        kicker: '方案比较',
        title: 'API-Route 与其他方案',
        body: '不同方案都有适合的使用场景。以下比较聚焦账户和接入方式，不对供应商服务质量作排名。',
        officialApis: {
          title: 'API-Route 与官方模型 API 的区别',
          body: 'OpenAI、Anthropic、Google 等官方 API 是模型供应商直接提供的服务。API-Route 的重点是用一个账户减少同时接入多个供应商时的管理工作。',
          headers: ['比较项', 'API-Route', '官方模型 API'],
          rows: [
            ['供应商账户', '一个 API-Route 账户', '需要分别注册所选供应商'],
            ['Base URL 和 API Key', '一套兼容接口和密钥流程', '各供应商使用自己的接口与凭证'],
            ['模型价格', '在同一定价页统一比较', '分别查看各供应商定价页'],
            ['余额与调用日志', '在同一账户中管理', '分别在各供应商控制台管理'],
            ['客户端配置', '复用兼容接口并切换模型 ID', '分别配置不同供应商接入'],
          ],
        },
        openRouter: {
          title: 'API-Route 是 OpenRouter 的替代方案吗？',
          body: 'API-Route 和 OpenRouter 都面向需要统一调用多个模型的用户。OpenRouter 同样提供多模型统一接口、OpenAI SDK 兼容和供应商路由，这些能力并非 API-Route 独有。',
          headers: ['比较项', 'API-Route', 'OpenRouter'],
          rows: [
            ['多模型统一接口', '调用 API-Route 当前上架的模型', '提供自己的模型目录和供应商路由'],
            ['OpenAI API 兼容性', '提供 OpenAI 兼容接口和 Base URL', '支持 OpenAI SDK 兼容调用'],
            ['支付方式', '以充值页当前显示的可用方式为准', '请以 OpenRouter 当前账单页面支持的方式和地区为准'],
            ['套餐与余额', '支持账户余额和当前可购买的使用套餐', '请对照 OpenRouter 当前积分和账单条款'],
            ['客户端接入', '为 Codex、Claude Code 等支持工具提供配置流程', '需结合客户端和 OpenRouter 当前文档确认自定义接口支持'],
            ['本地化与支持', '提供四种语言页面及网站当前显示的支持渠道', '请查看 OpenRouter 当前提供的语言和官方支持渠道'],
          ],
          conclusion: '两者服务方向相似。用户可以根据支付方式、套餐和余额偏好、客户端配置、本地化支持，以及实际需要的模型进行选择。',
        },
      },
      start: {
        kicker: '开始使用',
        title: '开始使用',
        modesTitle: '选择使用方式',
        modes: [
          ['AI Chat', '直接使用网站提供的网页版聊天，并继续受当前可用模型范围约束。'],
          ['API 接入', '通过 API 将应用、SDK、脚本或支持的客户端接入 API-Route。'],
          ['独立平台', '需要为自己的用户提供独立入口时，可使用现有独立平台方案。'],
        ],
        nextTitle: '下一步',
        body: '继续查看详细配置、比较当前模型成本，或创建账户开始使用。',
        actions: [
          ['/docs/quickstart', '查看快速开始', 'primary'],
          ['/pricing', '比较模型价格', 'secondary'],
          ['/register', '注册账户', 'secondary'],
        ],
      },
    },
  },
  ja: {
    navigation: DOCS_NAVIGATION_COPY.ja,
    overview: {
      eyebrow: '製品概要',
      title: 'API-Route とは？',
      description: 'API-Route は、モデル呼び出し、ルーティング、料金、残高、利用ログをひとつのアカウントにまとめる OpenAI 互換のマルチモデル AI API です。',
      seoTitle: DOCS_OVERVIEW_SEO_COPY.ja.title,
      seoDescription: DOCS_OVERVIEW_SEO_COPY.ja.description,
      directory: [
        ['what-is', 'API-Route とは'],
        ['how-it-works', 'API-Route の仕組み'],
        ['routing-failover', 'マルチルートとフェイルオーバー'],
        ['pricing-cost', '料金とコスト'],
        ['alternatives', 'API-Route と他の選択肢'],
        ['start', '利用を開始'],
      ],
      whatIs: {
        kicker: 'API-Route とは',
        title: 'API-Route とは',
        positionTitle: '製品の位置づけ',
        paragraphs: [
          'API-Route は OpenAI 互換のマルチモデル AI API です。共通の Base URL と API キーを使い、対応モデルを呼び出せるため、プロバイダーごとの接続設定を個別に管理する手間を減らせます。',
          'モデル料金、アカウント残高、プラン、利用ログも同じアカウントで確認できます。',
        ],
        points: [
          'ひとつの Base URL と API キーで対応モデルを利用',
          'モデル料金と提供状況をまとめて確認',
          '残高と利用ログを一元管理',
        ],
        audienceTitle: '対象ユーザー、モデル、アプリ',
        audienceBody: 'AI アプリ開発、SaaS 連携、複数モデルを統一的に利用したい開発者やチームに適しています。',
        audienceItems: [
          ['モデル', '対応モデルは変更されるため、固定リストではなく料金ページの最新表示を確認してください。'],
          ['ツール', 'Codex、Claude Code、LibreChat、VS Code、およびアプリページに掲載されているツールの接続案内を用意しています。'],
        ],
        links: [
          ['/pricing', 'モデルと料金を見る'],
          ['/apps', '対応アプリを見る'],
          ['/docs/quickstart', 'クイックスタートを見る'],
        ],
      },
      workflow: {
        kicker: 'API-Route の仕組み',
        title: 'API-Route の仕組み',
        stepsTitle: '4 ステップの利用フロー',
        steps: [
          ['アカウントを登録', '残高と API キーを管理するアカウントを作成します。Google、X、GitHub アカウントでの登録・ログインにも対応しています。'],
          ['残高をチャージ、またはプランを購入', 'チャージ画面に表示される支払い方法を使い、従量残高または利用可能なプランを選びます。'],
          ['API キーを作成', 'API キーページで有効なキーを作り、安全に保存します。'],
          ['モデルを選んで呼び出す', 'キーで利用できる正確なモデル ID を指定し、設定済みエンドポイントへリクエストします。'],
        ],
        keySettingsTitle: 'API キーの管理とアクセス制御',
        keySettingsBody: 'API キーごとに設定を分け、アプリや環境に合わせて利用上限とアクセス条件を管理できます。',
        keySettingsItems: [
          ['クォータと有効期限', '無制限または固定クォータを設定し、期限日時または無期限を選べます。'],
          ['ルーティング優先順位', 'トークン単価優先または呼び出し単価優先を選べます。実際のルートは、選択したモデルと現在のバックエンド状況により決まります。'],
          ['モデル許可リスト', '現在公開中の指定モデルだけを利用可能にできます。空欄の場合も、キーグループと公開状況による制限は適用されます。'],
          ['IP 許可リスト', '複数の IP アドレスまたは CIDR を指定できます。空欄の場合は接続元 IP を制限しません。'],
          ['キーグループと対応モデル', 'キーグループが提供されている場合は、グループを選んでキーを作成し、料金と現在利用できるモデルを確認できます。'],
          ['キーのライフサイクル', 'キーごとに編集、有効化、無効化、削除ができます。新しいシークレットは一度だけ表示されるため、安全に保存してください。'],
        ],
        keySettingsLinks: [['/tokens', 'API キーを管理']],
        interfaceTitle: '統一インターフェース',
        interfaceBody: 'Base URL は接続先、API キーは認証、モデル ID は利用モデルの選択に使います。残高、利用量、リクエストログは同じアカウントで管理されます。',
        interfaceItems: [
          ['Base URL', 'OpenAI 互換接続に対応するクライアントや SDK が利用するエンドポイントです。'],
          ['API キー', 'API リクエストを認証するためにアカウントで作成する認証情報です。'],
          ['モデル ID', 'リクエストごとにモデルを指定する現在の正確な識別子です。'],
          ['アカウントとログ', '残高、利用量、リクエスト履歴をまとめて確認できます。'],
        ],
        link: 'クイックスタートへ進む',
      },
      routing: {
        kicker: 'マルチルートとフェイルオーバー',
        title: 'マルチルートとフェイルオーバー',
        multiRouteTitle: 'マルチルートの仕組み',
        multiRouteBody: '同じモデルに、ひとつまたは複数の利用可能なルートノードを設定できます。料金ページの「1 route」「2 routes」「3 routes」は、そのモデルで現在利用できるルート数を示します。',
        multiRouteItems: [
          '複数ルートは、単一の上流ノードへの依存を減らします。',
          'すべてのモデルに複数ルートがあるわけではありません。',
          '実際のルート数は料金ページの最新表示を確認してください。',
        ],
        failoverTitle: 'フェイルオーバーと能力の範囲',
        failoverBody: '現在のルートでエラー、タイムアウト、一時的な利用不可が発生した場合、既定のルーティング方針に従って再試行するか、別の利用可能なルートへ切り替えられます。',
        failoverItems: [
          'マルチルートは単一ノード障害の影響を抑えるのに役立ちます。',
          'フェイルオーバーは無障害を保証するものではなく、すべてのモデルに常時予備ルートがあるわけではありません。',
          '実際のルート提供状況はモデルや時期によって変わります。',
        ],
        flow: ['ユーザーのリクエスト', '利用可能なルートを選択', '異常時に再試行または予備ルートへ切り替え'],
      },
      pricing: {
        kicker: '料金とコスト',
        title: '料金とコスト',
        billingTitle: 'API の課金方法',
        billingBody: '課金単位はモデルによって異なります。実際の請求は、料金ページ、アカウント記録、利用ログの内容に基づきます。',
        billingItems: [
          ['入力トークン', 'トークン課金モデルへ送るテキストやコンテキストです。'],
          ['出力トークン', 'モデルが生成したテキストです。'],
          ['キャッシュ料金', '対応モデルではキャッシュ読取と作成が別料金になる場合があります。'],
          ['呼び出し・メディア仕様課金', '画像、音声、動画などは、呼び出し回数、時間、解像度、その他の掲載仕様で課金される場合があります。'],
          ['残高とプラン', '利用量はアカウント残高、または利用可能なプランの条件と上限に従って消費されます。'],
        ],
        links: [
          ['/pricing', 'モデル料金を比較'],
          ['/packages', 'プランを見る'],
        ],
        lowerTitle: '公式参考価格より安くなる場合がある理由',
        lowerBody: 'API-Route は複数の利用可能な上流供給元とルートノードに接続します。供給元ごとに、一括調達、提携精算、コスト構造が異なる場合があります。',
        lowerItems: [
          ['単位コスト', '呼び出し量の集約、共通インフラ、自動ルーティングにより、1 回あたりのコストを抑えられる場合があります。'],
          ['公式参考価格', '公式価格はモデル提供元が公開する小売価格で、料金比較の基準として使用します。'],
          ['ルート差', 'ルートによって料金、遅延、上限、コンテキスト能力、提供状況が異なる場合があります。低価格でも、公式直結とすべての特性が同一という意味ではありません。'],
        ],
      },
      alternatives: {
        kicker: '選択肢の比較',
        title: 'API-Route と他の選択肢',
        body: 'どの選択肢にも適した用途があります。以下では、サービス品質を順位づけせず、アカウント管理と接続方法の違いを比較します。',
        officialApis: {
          title: 'API-Route と公式モデル API の違い',
          body: 'OpenAI、Anthropic、Google などの公式 API は各社が直接提供するサービスです。API-Route は、複数プロバイダー利用時の管理をひとつのアカウントにまとめます。',
          headers: ['比較項目', 'API-Route', '公式モデル API'],
          rows: [
            ['プロバイダーアカウント', 'API-Route のひとつのアカウント', '利用する各プロバイダーで個別登録'],
            ['Base URL と API キー', '共通の互換 API とキー管理', 'プロバイダーごとのエンドポイントと認証情報'],
            ['モデル料金', 'ひとつの料金ページで比較', '各プロバイダーの料金ページで確認'],
            ['残高と利用ログ', '同じアカウントで管理', '各プロバイダーのコンソールで管理'],
            ['クライアント設定', '互換接続を再利用しモデル ID を変更', 'プロバイダーごとに接続を設定'],
          ],
        },
        openRouter: {
          title: 'API-Route は OpenRouter の代替になりますか？',
          body: 'API-Route と OpenRouter は、複数モデルを統一的に利用したいユーザー向けという点で方向性が似ています。OpenRouter もマルチモデル API、OpenAI SDK 互換、プロバイダールーティングを提供しており、これらは API-Route だけの機能ではありません。',
          headers: ['比較項目', 'API-Route', 'OpenRouter'],
          rows: [
            ['マルチモデル統一 API', 'API-Route に現在掲載されているモデルを利用', '独自のモデルカタログとプロバイダールーティングを提供'],
            ['OpenAI API 互換性', 'OpenAI 互換 API と Base URL を提供', 'OpenAI SDK 互換利用に対応'],
            ['支払い方法', 'チャージ画面に現在表示される方法を利用', '対応方法と地域は現在の OpenRouter 請求ページで確認'],
            ['プランと残高', 'アカウント残高と利用可能なプランに対応', '現在の OpenRouter クレジット・請求条件と比較'],
            ['クライアント接続', 'Codex、Claude Code など対応ツール向けの設定を提供', 'クライアントと OpenRouter の最新案内でカスタム接続対応を確認'],
            ['ローカライズとサポート', '4 言語のページとサイトに表示されるサポート窓口を提供', 'OpenRouter の提供言語と公式サポート窓口を確認'],
          ],
          conclusion: '両サービスの方向性は似ています。支払い方法、プランと残高、クライアント設定、ローカライズ、実際に必要なモデルを基準に選択してください。',
        },
      },
      start: {
        kicker: '利用を開始',
        title: '利用を開始',
        modesTitle: '利用方法の選択',
        modes: [
          ['AI Chat', 'サイトの Web チャットから、その製品で現在利用できるモデルを使います。'],
          ['API 接続', 'アプリ、SDK、スクリプト、対応クライアントを API に接続します。'],
          ['独立プラットフォーム', '自分のユーザー向けに独立した入口が必要な場合は、既存の独立サイト機能を利用します。'],
        ],
        nextTitle: '次のステップ',
        body: '詳しい設定を確認し、モデル料金を比較するか、アカウントを作成してください。',
        actions: [
          ['/docs/quickstart', 'クイックスタートを見る', 'primary'],
          ['/pricing', 'モデル料金を比較', 'secondary'],
          ['/register', 'アカウント登録', 'secondary'],
        ],
      },
    },
  },
  ko: {
    navigation: DOCS_NAVIGATION_COPY.ko,
    overview: {
      eyebrow: '제품 개요',
      title: 'API-Route란 무엇인가요?',
      description: 'API-Route는 모델 호출, 라우팅, 가격, 잔액, 사용 로그를 하나의 계정에서 관리하는 OpenAI 호환 멀티 모델 AI API입니다.',
      seoTitle: DOCS_OVERVIEW_SEO_COPY.ko.title,
      seoDescription: DOCS_OVERVIEW_SEO_COPY.ko.description,
      directory: [
        ['what-is', 'API-Route란'],
        ['how-it-works', 'API-Route 작동 방식'],
        ['routing-failover', '다중 라우팅과 장애 전환'],
        ['pricing-cost', '가격과 비용'],
        ['alternatives', 'API-Route와 다른 선택지'],
        ['start', '시작하기'],
      ],
      whatIs: {
        kicker: 'API-Route란',
        title: 'API-Route란',
        positionTitle: '제품의 역할',
        paragraphs: [
          'API-Route는 OpenAI 호환 멀티 모델 AI API입니다. 하나의 Base URL과 API 키로 지원 모델을 호출해 공급자별 연결 설정을 따로 관리하는 부담을 줄일 수 있습니다.',
          '모델 가격, 계정 잔액, 플랜, 요청 로그도 같은 계정에서 확인할 수 있습니다.',
        ],
        points: [
          '하나의 Base URL과 API 키로 지원 모델 호출',
          '모델 가격과 제공 상태를 한곳에서 확인',
          '잔액과 요청 로그 통합 관리',
        ],
        audienceTitle: '대상 사용자, 모델, 애플리케이션',
        audienceBody: 'AI 애플리케이션 개발, SaaS 연동, 여러 모델을 하나의 방식으로 호출하려는 개발자와 팀에 적합합니다.',
        audienceItems: [
          ['모델', '지원 모델은 변경될 수 있으므로 고정 목록 대신 가격 페이지의 실시간 표시를 기준으로 확인하세요.'],
          ['도구', 'Codex, Claude Code, LibreChat, VS Code 및 앱 페이지에 등록된 다른 도구의 연결 안내를 제공합니다.'],
        ],
        links: [
          ['/pricing', '모델과 가격 보기'],
          ['/apps', '지원 앱 보기'],
          ['/docs/quickstart', '빠른 시작 보기'],
        ],
      },
      workflow: {
        kicker: 'API-Route 작동 방식',
        title: 'API-Route 작동 방식',
        stepsTitle: '4단계 사용 흐름',
        steps: [
          ['계정 가입', '잔액과 API 키를 관리할 계정을 만듭니다. Google, X 또는 GitHub 계정으로 가입하고 로그인할 수도 있습니다.'],
          ['잔액 충전 또는 플랜 구매', '충전 페이지에 현재 표시되는 결제 방식을 사용한 뒤 종량 잔액 또는 이용 가능한 플랜을 선택합니다.'],
          ['API 키 생성', 'API 키 페이지에서 활성 키를 만들고 안전하게 저장합니다.'],
          ['모델 선택 후 호출', '키에서 사용할 수 있는 정확한 모델 ID를 지정해 설정된 엔드포인트로 요청합니다.'],
        ],
        keySettingsTitle: 'API 키 관리 및 접근 제어',
        keySettingsBody: 'API 키마다 설정을 분리해 애플리케이션과 환경별로 사용 한도와 접근 조건을 관리할 수 있습니다.',
        keySettingsItems: [
          ['할당량 및 만료', '무제한 또는 고정 할당량을 설정하고, 특정 만료 시간이나 무기한 사용을 선택할 수 있습니다.'],
          ['라우팅 우선순위', '토큰 가격 우선 또는 호출당 가격 우선을 선택할 수 있습니다. 실제 라우트는 선택한 모델과 현재 백엔드 상태에 따라 달라집니다.'],
          ['모델 허용 목록', '현재 등록된 모델 중 지정한 모델만 호출하도록 제한할 수 있습니다. 비워 두어도 키 그룹과 현재 등록 상태에 따른 제한은 적용됩니다.'],
          ['IP 허용 목록', '하나 이상의 IP 주소 또는 CIDR 대역을 지정할 수 있습니다. 비워 두면 접속 IP를 제한하지 않습니다.'],
          ['키 그룹 및 지원 모델', '키 그룹이 제공되는 경우 그룹별 키를 생성하고 가격과 현재 호출 가능한 모델을 확인할 수 있습니다.'],
          ['키 수명 주기', '키별로 수정, 활성화, 비활성화 또는 삭제할 수 있습니다. 새 시크릿은 한 번만 표시되므로 안전하게 보관해야 합니다.'],
        ],
        keySettingsLinks: [['/tokens', 'API 키 관리']],
        interfaceTitle: '통합 인터페이스 방식',
        interfaceBody: 'Base URL은 연결 주소, API 키는 요청 인증, 모델 ID는 모델 선택에 사용합니다. 잔액, 사용량, 요청 로그는 같은 계정에서 관리됩니다.',
        interfaceItems: [
          ['Base URL', 'OpenAI 호환 연결을 지원하는 클라이언트와 SDK가 사용하는 엔드포인트입니다.'],
          ['API 키', 'API 요청 인증을 위해 계정에서 생성하는 자격 증명입니다.'],
          ['모델 ID', '요청에서 모델을 선택할 때 사용하는 현재의 정확한 식별자입니다.'],
          ['계정과 로그', '잔액, 사용량, 요청 기록을 한곳에서 확인합니다.'],
        ],
        link: '빠른 시작으로 이동',
      },
      routing: {
        kicker: '다중 라우팅과 장애 전환',
        title: '다중 라우팅과 장애 전환',
        multiRouteTitle: '다중 라우팅 구조',
        multiRouteBody: '같은 모델에 하나 이상의 사용 가능한 라우트 노드를 구성할 수 있습니다. 가격 페이지의 “1 route”, “2 routes”, “3 routes”는 해당 모델에서 현재 사용할 수 있는 라우트 수를 뜻합니다.',
        multiRouteItems: [
          '여러 라우트는 하나의 업스트림 노드에 대한 의존도를 낮출 수 있습니다.',
          '모든 모델이 여러 라우트를 제공하는 것은 아닙니다.',
          '실제 라우트 수는 가격 페이지의 실시간 표시를 기준으로 합니다.',
        ],
        failoverTitle: '장애 전환과 기능 범위',
        failoverBody: '현재 라우트에서 오류, 시간 초과, 일시적인 이용 불가가 발생하면 정해진 라우팅 정책에 따라 재시도하거나 다른 사용 가능한 라우트로 전환할 수 있습니다.',
        failoverItems: [
          '다중 라우팅은 단일 노드 장애의 영향을 줄이는 데 도움이 됩니다.',
          '장애 전환이 무중단을 보장하거나 모든 모델에 항상 예비 라우트가 있음을 의미하지는 않습니다.',
          '실제 라우트 제공 상태는 모델과 시점에 따라 달라집니다.',
        ],
        flow: ['사용자 요청', '사용 가능한 라우트 선택', '오류 시 재시도 또는 예비 라우트 전환'],
      },
      pricing: {
        kicker: '가격과 비용',
        title: '가격과 비용',
        billingTitle: 'API 과금 방식',
        billingBody: '과금 단위는 모델마다 다릅니다. 실제 차감액은 가격 페이지, 계정 기록, 요청 로그를 기준으로 합니다.',
        billingItems: [
          ['입력 토큰', '토큰 과금 모델에 보내는 텍스트 또는 컨텍스트입니다.'],
          ['출력 토큰', '모델이 생성한 텍스트입니다.'],
          ['캐시 비용', '지원 모델은 캐시 읽기와 캐시 생성을 별도로 과금할 수 있습니다.'],
          ['호출 및 미디어 사양 과금', '이미지, 오디오, 비디오 등은 호출, 시간, 해상도 또는 표에 표시된 다른 사양으로 과금될 수 있습니다.'],
          ['잔액과 플랜', '사용량은 계정 잔액 또는 이용 가능한 플랜의 조건과 한도에 따라 차감됩니다.'],
        ],
        links: [
          ['/pricing', '모델 가격 비교'],
          ['/packages', '플랜 보기'],
        ],
        lowerTitle: '공식 참고 가격보다 낮을 수 있는 이유',
        lowerBody: 'API-Route는 여러 사용 가능한 업스트림 공급 채널과 라우트 노드에 연결합니다. 채널마다 대량 구매, 제휴 정산, 비용 구조가 다를 수 있습니다.',
        lowerItems: [
          ['단위 비용', '호출량 집계, 공유 인프라, 자동 라우팅으로 호출당 비용을 낮출 수 있습니다.'],
          ['공식 참고 가격', '공식 가격은 모델 공급자가 공개한 소매 가격이며 비용 비교 기준으로 사용합니다.'],
          ['라우트 차이', '라우트마다 가격, 지연 시간, 한도, 컨텍스트 기능, 가용성이 다를 수 있습니다. 낮은 가격이 공식 직접 연결과 모든 특성이 같다는 뜻은 아닙니다.'],
        ],
      },
      alternatives: {
        kicker: '선택지 비교',
        title: 'API-Route와 다른 선택지',
        body: '각 방식에는 적합한 사용 사례가 있습니다. 아래 비교는 공급자 서비스 품질의 순위를 매기지 않고 계정 관리와 연결 방식의 차이에 초점을 둡니다.',
        officialApis: {
          title: 'API-Route와 공식 모델 API의 차이',
          body: 'OpenAI, Anthropic, Google 등의 공식 API는 각 공급자가 직접 제공하는 서비스입니다. API-Route는 여러 공급자를 사용할 때 필요한 관리를 하나의 계정으로 모으는 데 초점을 둡니다.',
          headers: ['비교 항목', 'API-Route', '공식 모델 API'],
          rows: [
            ['공급자 계정', '하나의 API-Route 계정', '선택한 공급자마다 별도 가입'],
            ['Base URL과 API 키', '하나의 호환 API와 키 관리 흐름', '공급자별 엔드포인트와 인증 정보'],
            ['모델 가격', '하나의 가격 페이지에서 비교', '각 공급자 가격 페이지에서 확인'],
            ['잔액과 요청 로그', '한 계정에서 통합 관리', '각 공급자 콘솔에서 개별 관리'],
            ['클라이언트 설정', '호환 연결을 재사용하고 모델 ID 전환', '공급자 연동을 각각 설정'],
          ],
        },
        openRouter: {
          title: 'API-Route는 OpenRouter의 대안인가요?',
          body: 'API-Route와 OpenRouter는 여러 모델을 통합해 사용하려는 이용자를 위한 서비스라는 점에서 방향이 비슷합니다. OpenRouter도 멀티 모델 통합 인터페이스, OpenAI SDK 호환, 공급자 라우팅을 제공하므로 이러한 기능은 API-Route만의 기능이 아닙니다.',
          headers: ['비교 항목', 'API-Route', 'OpenRouter'],
          rows: [
            ['멀티 모델 통합 API', 'API-Route에 현재 등록된 모델 이용', '자체 모델 카탈로그와 공급자 라우팅 제공'],
            ['OpenAI API 호환성', 'OpenAI 호환 API와 Base URL 제공', 'OpenAI SDK 호환 사용 지원'],
            ['결제 방식', '충전 페이지에 현재 표시되는 방식을 사용', '지원 방식과 지역은 현재 OpenRouter 결제 페이지에서 확인'],
            ['플랜과 잔액', '계정 잔액과 현재 이용 가능한 플랜 지원', '현재 OpenRouter 크레딧 및 결제 조건과 비교'],
            ['클라이언트 연결', 'Codex, Claude Code 등 지원 도구용 설정 흐름 제공', '클라이언트와 OpenRouter의 최신 안내에서 사용자 지정 연결 지원 확인'],
            ['현지화와 지원', '4개 언어 페이지와 사이트에 표시된 지원 채널 제공', 'OpenRouter의 현재 언어와 공식 지원 채널 확인'],
          ],
          conclusion: '두 서비스의 방향은 비슷합니다. 결제 방식, 플랜과 잔액 선호, 클라이언트 설정, 현지화 지원, 실제로 필요한 모델을 기준으로 선택할 수 있습니다.',
        },
      },
      start: {
        kicker: '시작하기',
        title: '시작하기',
        modesTitle: '사용 방식 선택',
        modes: [
          ['AI Chat', '사이트 웹 채팅에서 해당 제품에 현재 제공되는 모델을 사용합니다.'],
          ['API 연동', '애플리케이션, SDK, 스크립트 또는 지원 클라이언트를 API에 연결합니다.'],
          ['독립 플랫폼', '자체 사용자용 별도 진입점이 필요할 때 기존 독립 사이트 기능을 사용합니다.'],
        ],
        nextTitle: '다음 단계',
        body: '상세 설정을 확인하고 현재 모델 비용을 비교하거나 계정을 만들어 시작하세요.',
        actions: [
          ['/docs/quickstart', '빠른 시작 보기', 'primary'],
          ['/pricing', '모델 가격 비교', 'secondary'],
          ['/register', '계정 가입', 'secondary'],
        ],
      },
    },
  },
};

export function getDocsCopy(language) {
  return DOCS_COPY[language] || DOCS_COPY.en;
}
