export const ENTERPRISE_COPY = {
  en: {
    keywords: 'enterprise AI API,enterprise AI API solutions,enterprise LLM API,production AI API,stable AI API,high-volume AI API,multi-model AI API,AI API integration,AI API migration support,AI API operational support,capacity planning,API-Route',
    title: 'Enterprise AI API for stable production workloads',
    description: 'Connect to leading AI models through one unified API, with an onboarding plan shaped around your usage, reliability, and technical requirements.',
    metaTitle: 'Enterprise AI API Solutions',
    metaDescription: 'Get a tailored enterprise AI API plan focused on production stability, routing resilience, capacity planning, and dedicated operational support.',
    audience: 'For teams running AI APIs in production, scaling sustained usage, or planning a migration that needs dedicated technical ownership.',
    valueTitle: 'Built around the needs of production teams',
    reasons: [
      {
        title: 'A stability plan for your workload',
        body: 'We assess models, traffic volume, peak demand, upstream capacity, routing, and failover options to reduce uncertainty in production.',
      },
      {
        title: 'A solution shaped around your stack',
        body: 'Model selection, API key and usage management, integration, and migration are planned around your architecture, budget, and rollout.',
      },
      {
        title: 'Dedicated after-sales operations',
        body: 'A designated contact follows onboarding and ongoing operations, helping investigate request issues and adjust the solution as needs change.',
      },
    ],
    capabilities: [
      'Multi-route traffic and failover',
      'Stable upstream access and capacity planning',
      'API key and usage management',
      'Dedicated onboarding and migration support',
    ],
    comparison: {
      title: 'Standard access vs. enterprise',
      standardTitle: 'Standard self-service',
      standardBody: 'Standard model and routing options, self-service onboarding, documentation, and regular support channels.',
      enterpriseTitle: 'Enterprise integration',
      enterpriseBody: 'A tailored stability plan, dedicated implementation and operational follow-up, plus pricing reviewed against actual scale.',
    },
    formTitle: 'Tell us what your team needs',
    formDescription: 'A dedicated contact will review your models, usage, peak traffic, and current architecture, then provide an integration plan and pricing.',
    fields: {
      company: 'Company or team name',
      contact: 'Contact person',
      email: 'Work email',
      volume: 'Expected monthly usage or budget',
      requirements: 'Models and requirements',
    },
    placeholders: {
      company: 'Company or team',
      contact: 'Your name',
      email: 'name@company.com',
      volume: 'For example: $5,000/month or 2B tokens',
      requirements: 'Models, current setup, traffic pattern, migration timing, or stability requirements',
    },
    submit: 'Submit enterprise requirements',
    submitting: 'Preparing email...',
    emailNotice: 'This opens your email app. Your information is not sent until you send the email.',
    success: 'Your email draft is ready. Send it to complete the inquiry.',
    failure: 'We could not open your email app. Contact {{email}} directly.',
    validation: {
      required: 'Complete this field.',
      email: 'Enter a valid work email.',
    },
    emailSubject: 'Enterprise AI API inquiry - {{company}}',
    responseNote: 'We will recommend an integration approach and pricing based on your models, usage, and reliability requirements.',
    trust: ['Multi-model access', 'Automatic failover', 'Flexible billing', 'Dedicated technical support'],
  },
  zh: {
    keywords: '企业 AI API,企业级大模型 API,企业多模型 API,统一 AI API 企业方案,高并发 AI API,大用量 AI API,AI API 稳定性方案,AI API 定制接入,AI API 迁移服务,企业 API 技术支持,企业 AI API 运维,API-Route',
    title: '企业级 AI API，面向稳定业务场景',
    description: '通过统一接口接入主流 AI 模型，并根据企业用量、稳定性和技术需求提供接入方案。',
    metaTitle: '企业 AI API 接入方案',
    metaDescription: '获取面向生产业务的企业 AI API 定制方案，重点覆盖稳定性、路由与容量评估，以及专人售后运维。',
    audience: '适合将 AI API 用于生产业务、调用规模持续增长，或需要迁移与定制路由的企业团队。',
    valueTitle: '企业方案解决的不只是接入',
    reasons: [
      {
        title: '稳定性方案',
        body: '根据所需模型、调用规模和峰值流量，评估上游容量、多路由与故障切换策略，降低生产调用的不确定性。',
      },
      {
        title: '量身定制',
        body: '结合现有架构、预算和上线计划，制定模型选择、API Key 与用量管理、接入和迁移方案。',
      },
      {
        title: '专人售后运维',
        body: '由固定人员持续跟进接入、迁移和运行问题，协助排查调用异常，并根据业务变化调整方案。',
      },
    ],
    capabilities: [
      '多路由与故障切换',
      '稳定上游与容量评估',
      'API Key 与用量管理',
      '专属接入和迁移支持',
    ],
    comparison: {
      title: '普通使用与企业方案',
      standardTitle: '普通自助使用',
      standardBody: '使用标准模型与路由配置，自助开通和接入，通过文档及常规渠道解决问题。',
      enterpriseTitle: '企业接入方案',
      enterpriseBody: '按需制定稳定性方案，专人跟进实施、迁移与后续运维，并结合实际规模评估报价。',
    },
    formTitle: '提交企业需求',
    formDescription: '提交后，专人将结合你的模型、用量、峰值流量和现有架构，提供接入方案与报价。',
    fields: {
      company: '公司或团队名称',
      contact: '联系人',
      email: '工作邮箱',
      volume: '预计月用量或预算',
      requirements: '所需模型与需求说明',
    },
    placeholders: {
      company: '公司或团队名称',
      contact: '你的姓名',
      email: 'name@company.com',
      volume: '例如：每月 3 万元或 20 亿 tokens',
      requirements: '所需模型、现有接入方式、流量特征、迁移时间或稳定性要求',
    },
    submit: '提交企业需求',
    submitting: '正在准备邮件...',
    emailNotice: '提交后将打开你的邮件应用；只有确认发送后，信息才会送达我们。',
    success: '邮件草稿已准备好，请在邮件应用中发送以完成咨询。',
    failure: '无法打开邮件应用，请直接联系 {{email}}。',
    validation: {
      required: '请填写此项。',
      email: '请输入有效的工作邮箱。',
    },
    emailSubject: '企业 AI API 咨询 - {{company}}',
    responseNote: '我们将根据模型、用量和稳定性要求提供接入建议与报价。',
    trust: ['多模型接入', '自动故障切换', '灵活结算', '专属技术支持'],
  },
  ja: {
    keywords: '企業向け AI API,エンタープライズ AI API,企業向け LLM API,本番 AI API,安定した AI API,大規模 AI API,マルチモデル API,AI API 導入支援,AI API 移行支援,AI API 運用サポート,容量計画,API-Route',
    title: '安定運用を支える、企業向け AI API',
    description: '主要な AI モデルをひとつの API で接続し、利用規模、安定性、技術要件に合わせた導入プランをご提案します。',
    metaTitle: '企業向け AI API 導入プラン',
    metaDescription: '本番運用の安定性、ルーティング、容量設計、専任の運用支援を重視した企業向け AI API 導入プランをご提案します。',
    audience: 'AI API を本番環境で運用するチーム、継続的な利用増加に対応したい企業、専任支援を受けながら移行したい企業向けです。',
    valueTitle: '本番運用を見据えた企業向け支援',
    reasons: [
      {
        title: 'ワークロードに合わせた安定性設計',
        body: '対象モデル、利用量、ピーク時の負荷をもとに、上流容量、複数ルート、障害時の切り替え方法を検討します。',
      },
      {
        title: '環境に合わせた個別プラン',
        body: '既存構成、予算、導入時期に合わせて、モデル選定、API キーと利用量管理、接続・移行方法を設計します。',
      },
      {
        title: '専任担当による導入後の運用支援',
        body: '固定の担当者が導入から運用まで継続してフォローし、呼び出し時の問題調査や要件変化に応じた調整を支援します。',
      },
    ],
    capabilities: [
      '複数ルートと障害時の切り替え',
      '安定した上流接続と容量設計',
      'API キーと利用量の管理',
      '専任の導入・移行サポート',
    ],
    comparison: {
      title: '通常利用と企業向けプランの違い',
      standardTitle: '通常のセルフサービス',
      standardBody: '標準のモデル・ルート設定を使い、ドキュメントと通常のサポート窓口から自身で導入します。',
      enterpriseTitle: '企業向け導入プラン',
      enterpriseBody: '安定性を考慮した個別設計、導入・移行・運用の専任支援、実際の利用規模に応じたお見積もりを提供します。',
    },
    formTitle: 'ご要件をお聞かせください',
    formDescription: '担当者がモデル、利用量、ピーク時の負荷、現在の構成を確認し、導入方法とお見積もりをご案内します。',
    fields: {
      company: '会社名またはチーム名',
      contact: 'ご担当者名',
      email: '勤務先メールアドレス',
      volume: '月間利用量またはご予算',
      requirements: '必要なモデルとご要件',
    },
    placeholders: {
      company: '会社名またはチーム名',
      contact: 'お名前',
      email: 'name@company.com',
      volume: '例：月額 5,000 USD、20 億 tokens',
      requirements: '対象モデル、現在の構成、トラフィック、移行時期、安定性の要件',
    },
    submit: '企業向け要件を送信',
    submitting: 'メールを準備中...',
    emailNotice: 'メールアプリが開きます。送信操作を行うまで情報は送られません。',
    success: 'メールの下書きを作成しました。送信してお問い合わせを完了してください。',
    failure: 'メールアプリを開けませんでした。{{email}} へ直接ご連絡ください。',
    validation: {
      required: 'この項目を入力してください。',
      email: '有効な勤務先メールアドレスを入力してください。',
    },
    emailSubject: '企業向け AI API のご相談 - {{company}}',
    responseNote: 'モデル、利用量、安定性の要件に応じて、導入方法とお見積もりをご案内します。',
    trust: ['マルチモデル接続', '自動フェイルオーバー', '柔軟な請求', '専任テクニカルサポート'],
  },
  ko: {
    keywords: '엔터프라이즈 AI API,기업용 AI API,기업용 LLM API,프로덕션 AI API,안정적인 AI API,대용량 AI API,멀티 모델 API,AI API 도입 지원,AI API 마이그레이션,AI API 운영 지원,용량 계획,API-Route',
    title: '안정적인 비즈니스를 위한 엔터프라이즈 AI API',
    description: '하나의 통합 API로 주요 AI 모델을 연결하고, 사용량과 안정성, 기술 요구사항에 맞는 도입 방안을 제안합니다.',
    metaTitle: '엔터프라이즈 AI API 도입 상담',
    metaDescription: '프로덕션 안정성, 라우팅과 용량 계획, 전담 운영 지원에 초점을 둔 맞춤형 엔터프라이즈 AI API 도입 방안을 상담하세요.',
    audience: 'AI API를 프로덕션에 사용하거나 지속적인 사용량 증가에 대응해야 하는 팀, 전담 지원과 함께 마이그레이션하려는 기업에 적합합니다.',
    valueTitle: '프로덕션 운영을 위한 엔터프라이즈 지원',
    reasons: [
      {
        title: '워크로드에 맞춘 안정성 계획',
        body: '필요한 모델, 호출 규모, 피크 트래픽을 기준으로 상위 용량, 다중 라우팅, 장애 전환 방식을 검토합니다.',
      },
      {
        title: '환경에 맞춘 맞춤형 설계',
        body: '현재 아키텍처, 예산, 출시 일정에 맞춰 모델 선택, API 키와 사용량 관리, 연동 및 마이그레이션 방안을 설계합니다.',
      },
      {
        title: '전담 담당자의 도입 후 운영 지원',
        body: '고정 담당자가 도입부터 운영까지 지속적으로 대응하며, 호출 문제 조사와 요구사항 변화에 따른 조정을 지원합니다.',
      },
    ],
    capabilities: [
      '다중 라우팅과 장애 전환',
      '안정적인 상위 연결과 용량 계획',
      'API 키와 사용량 관리',
      '전담 도입 및 마이그레이션 지원',
    ],
    comparison: {
      title: '일반 사용과 엔터프라이즈의 차이',
      standardTitle: '일반 셀프서비스',
      standardBody: '표준 모델과 라우팅 설정을 사용하며 문서와 일반 지원 채널을 통해 직접 도입합니다.',
      enterpriseTitle: '엔터프라이즈 도입',
      enterpriseBody: '안정성을 고려한 맞춤 설계, 도입·이전·운영 전담 지원, 실제 사용 규모를 반영한 견적을 제공합니다.',
    },
    formTitle: '팀의 요구사항을 알려주세요',
    formDescription: '전담 담당자가 모델, 사용량, 피크 트래픽, 현재 아키텍처를 검토한 뒤 도입 방안과 견적을 안내합니다.',
    fields: {
      company: '회사 또는 팀 이름',
      contact: '담당자',
      email: '업무용 이메일',
      volume: '예상 월 사용량 또는 예산',
      requirements: '필요한 모델 및 요구사항',
    },
    placeholders: {
      company: '회사 또는 팀 이름',
      contact: '이름',
      email: 'name@company.com',
      volume: '예: 월 5,000달러 또는 20억 tokens',
      requirements: '필요한 모델, 현재 구성, 트래픽, 이전 일정, 안정성 요구사항',
    },
    submit: '엔터프라이즈 요구사항 제출',
    submitting: '이메일 준비 중...',
    emailNotice: '이메일 앱이 열립니다. 직접 전송하기 전에는 정보가 전달되지 않습니다.',
    success: '이메일 초안을 준비했습니다. 전송하면 상담 접수가 완료됩니다.',
    failure: '이메일 앱을 열 수 없습니다. {{email}}로 직접 문의해 주세요.',
    validation: {
      required: '필수 항목입니다.',
      email: '올바른 업무용 이메일을 입력해 주세요.',
    },
    emailSubject: '엔터프라이즈 AI API 상담 - {{company}}',
    responseNote: '모델, 사용량, 안정성 요구사항을 바탕으로 도입 방안과 견적을 안내합니다.',
    trust: ['멀티 모델 연동', '자동 장애 전환', '유연한 결제', '전담 기술 지원'],
  },
};

export function getEnterpriseCopy(language) {
  return ENTERPRISE_COPY[language] || ENTERPRISE_COPY.en;
}
