export const PRICING_COPY = {
  zh: {
    title: 'AI API 价格对比、模型费率与 Token 成本',
    description: '比较 GPT、Claude、Gemini 等模型在 API-Route 的输入价格、输出价格、缓存费用、按次计费和官方参考价，快速估算 AI API Token 成本与不同模型费用。',
    tableCaption: 'API-Route 模型价格、缓存价格与官方参考价',
    snapshotUnit: 'USD / 每 100 万 Token',
    siteTokenHeader: 'API-Route · 输入 / 输出 · 每 100 万 Token',
    officialTokenHeader: '官方输入 / 输出 · USD / 每 100 万 Token',
    unitNote: '文本价格按 100 万 Token 展示；媒体模型按照表格中的调用次数、秒数或规格计费。',
    loadError: '价格数据加载失败，请稍后重试。',
    retry: '重试',
    compareTitle: '这张价格表适合比较什么',
    compareItems: [
      '文本模型的输入、输出和缓存成本',
      '长上下文和重复提示词对总成本的影响',
      '图片、音频、视频模型的按次、按秒或规格计费',
      '本站价格与公开官方参考价的差异',
    ],
    explainTitle: '价格表关键字段',
    explain: [
      ['输入价格', '用户提示词、上下文、工具输入和系统提示词消耗的价格。'],
      ['输出价格', '模型生成内容消耗的价格，通常和输入价格不同。'],
      ['缓存价格', '适合长上下文或重复前缀调用，用来降低重复读取成本。'],
      ['官方参考价', '用于对照公开官方价格，实际扣费以本站价格和调用日志为准。'],
    ],
    calculator: {
      title: 'Token 成本计算器',
      description: '选择按 Token 计费的模型，输入单次用量和请求次数。',
      model: '模型',
      inputTokens: '平均输入 Token',
      outputTokens: '平均输出 Token',
      cacheReadTokens: '平均缓存读取 Token（可选）',
      cacheCreationTokens: '平均缓存创建 Token（可选）',
      requests: '请求次数',
      estimatedTotal: '预计总费用',
      estimateNote: '此结果仅为估算值，实际费用以调用日志为准。缓存创建按表格中的默认缓存创建价格计算。',
      unavailable: '暂无可用于计算的按 Token 计费模型。',
    },
    faqTitle: 'AI API 价格对比 FAQ',
    questions: [
      ['如何比较 OpenAI、Claude 和 Gemini 的 API 价格？', '先看输入和输出 Token 单价，再结合缓存、按次计费、上下文长度和你的调用量估算总成本。'],
      ['AI API Token 成本怎么估算？', '文本调用成本约等于输入 Token 成本加输出 Token 成本，再加缓存相关费用；图片、音频、视频按页面表格的规格或按次价格计算。'],
      ['为什么要看官方参考价？', '官方参考价用于对照公开价格，实际扣费以 API-Route 页面价格、账户记录和调用日志为准。'],
    ],
  },
  en: {
    title: 'AI API Pricing Comparison and Token Costs',
    description: 'Compare input, output, cache, per-call, and official reference rates for models available on API-Route, then estimate AI API token costs.',
    tableCaption: 'API-Route model rates, cache rates, and official price references',
    snapshotUnit: 'USD per 1M tokens',
    siteTokenHeader: 'API-Route · Input / Output · per 1M tokens',
    officialTokenHeader: 'Official Input / Output · USD per 1M tokens',
    unitNote: 'Text prices are shown per 1M tokens. Media models use the call, second, or specification unit shown in the table.',
    loadError: 'Pricing data could not be loaded. Please try again.',
    retry: 'Retry',
    compareTitle: 'What this pricing table helps you compare',
    compareItems: [
      'Input, output, and cache costs for text models',
      'How long context and repeated prompts affect total cost',
      'Per-call, per-second, or specification pricing for media models',
      'API-Route rates against public official references',
    ],
    explainTitle: 'Key pricing fields',
    explain: [
      ['Input price', 'Cost for prompts, context, system messages, and tool input sent to a model.'],
      ['Output price', 'Cost for generated content, which often differs from input pricing.'],
      ['Cache price', 'Useful for long context or repeated prefixes, helping reduce repeated context cost.'],
      ['Official reference', 'A comparison with public official rates. Actual billing follows API-Route rates and usage logs.'],
    ],
    calculator: {
      title: 'Token Cost Calculator',
      description: 'Choose a token-priced model, then enter average usage per request and request volume.',
      model: 'Model',
      inputTokens: 'Average input tokens',
      outputTokens: 'Average output tokens',
      cacheReadTokens: 'Average cache read tokens (optional)',
      cacheCreationTokens: 'Average cache creation tokens (optional)',
      requests: 'Requests',
      estimatedTotal: 'Estimated total',
      estimateNote: 'This is an estimate. Actual charges follow usage logs. Cache creation uses the default cache creation rate shown in the table.',
      unavailable: 'No token-priced models are currently available for calculation.',
    },
    faqTitle: 'AI API Pricing Comparison FAQ',
    questions: [
      ['How do I compare OpenAI, Claude, and Gemini API pricing?', 'Start with input and output token rates, then include cache pricing, per-call models, context length, and expected request volume.'],
      ['How do I estimate AI API token cost?', 'For text models, estimate input token cost plus output token cost plus cache-related costs. Image, audio, and video models follow the displayed specification or per-call price.'],
      ['Why include official reference pricing?', 'Official references help compare public provider prices. Actual billing follows API-Route rates, account records, and usage logs.'],
    ],
  },
  ja: {
    title: 'AI API 料金比較・モデル単価・トークンコスト',
    description: 'API-Route で利用できるモデルの入力、出力、キャッシュ、回数課金、公式参考価格を比較し、AI API のトークンコストを見積もれます。',
    tableCaption: 'API-Route のモデル料金、キャッシュ料金、公式参考価格',
    snapshotUnit: '100 万トークンあたり（USD）',
    siteTokenHeader: 'API-Route・入力 / 出力・100 万トークンあたり',
    officialTokenHeader: '公式 入力 / 出力・100 万トークンあたり（USD）',
    unitNote: 'テキスト料金は 100 万トークン単位です。画像・音声・動画は、表に表示された呼び出し回数、秒数、仕様単位で課金されます。',
    loadError: '料金データを読み込めませんでした。もう一度お試しください。',
    retry: '再試行',
    compareTitle: 'この料金表で比較できること',
    compareItems: [
      'テキストモデルの入力、出力、キャッシュ費用',
      '長文コンテキストや繰り返しプロンプトが総費用に与える影響',
      '画像、音声、動画モデルの回数、秒数、仕様ごとの料金',
      'API-Route の料金と公開公式参考価格の差',
    ],
    explainTitle: '料金表の主な項目',
    explain: [
      ['入力料金', 'プロンプト、コンテキスト、システムメッセージ、ツール入力にかかる料金です。'],
      ['出力料金', 'モデルが生成した内容にかかる料金で、入力料金と異なることがあります。'],
      ['キャッシュ料金', '長いコンテキストや繰り返しの前置きで、再利用コストを抑えるための料金です。'],
      ['公式参考価格', '公開されている公式価格との比較です。実際の課金は API-Route の料金と利用ログに従います。'],
    ],
    calculator: {
      title: 'トークン費用計算ツール',
      description: 'トークン課金モデルを選び、1 回あたりの平均利用量と呼び出し回数を入力します。',
      model: 'モデル',
      inputTokens: '平均入力トークン',
      outputTokens: '平均出力トークン',
      cacheReadTokens: '平均キャッシュ読み取りトークン（任意）',
      cacheCreationTokens: '平均キャッシュ作成トークン（任意）',
      requests: '呼び出し回数',
      estimatedTotal: '見積もり合計',
      estimateNote: 'これは概算です。実際の料金は利用ログに従います。キャッシュ作成には表の標準キャッシュ作成料金を使用します。',
      unavailable: '計算に使えるトークン課金モデルがありません。',
    },
    faqTitle: 'AI API 料金比較 FAQ',
    questions: [
      ['OpenAI、Claude、Gemini の API 料金はどう比較しますか？', '入力と出力のトークン単価に加えて、キャッシュ料金、回数課金、コンテキスト長、想定呼び出し回数を合わせて確認します。'],
      ['AI API のトークンコストはどう見積もりますか？', 'テキストモデルでは入力費用、出力費用、キャッシュ関連費用を合計します。画像、音声、動画は表の仕様や回数単価に従います。'],
      ['公式参考価格は何に使いますか？', '公開されている公式価格との比較に使います。実際の課金は API-Route の料金、アカウント記録、利用ログに従います。'],
    ],
  },
  ko: {
    title: 'AI API 요금 비교, 모델 단가 및 토큰 비용',
    description: 'API-Route에서 제공하는 모델의 입력, 출력, 캐시, 호출당 요금과 공식 참고 가격을 비교하고 AI API 토큰 비용을 추정하세요.',
    tableCaption: 'API-Route 모델 요금, 캐시 요금 및 공식 참고 가격',
    snapshotUnit: '100만 토큰당 USD',
    siteTokenHeader: 'API-Route · 입력 / 출력 · 100만 토큰당',
    officialTokenHeader: '공식 입력 / 출력 · 100만 토큰당 USD',
    unitNote: '텍스트 요금은 100만 토큰 기준입니다. 미디어 모델은 표에 표시된 호출, 초 또는 사양 단위로 과금됩니다.',
    loadError: '요금 데이터를 불러오지 못했습니다. 다시 시도해 주세요.',
    retry: '다시 시도',
    compareTitle: '이 요금표에서 비교할 수 있는 항목',
    compareItems: [
      '텍스트 모델의 입력, 출력 및 캐시 비용',
      '긴 문맥과 반복 프롬프트가 총비용에 미치는 영향',
      '이미지, 오디오, 영상 모델의 호출당, 초당 또는 사양별 요금',
      'API-Route 요금과 공개 공식 참고 가격의 차이',
    ],
    explainTitle: '주요 요금 항목',
    explain: [
      ['입력 요금', '프롬프트, 문맥, 시스템 메시지, 도구 입력에 적용되는 비용입니다.'],
      ['출력 요금', '모델이 생성한 내용에 적용되는 비용이며 입력 요금과 다를 수 있습니다.'],
      ['캐시 요금', '긴 문맥이나 반복 프롬프트에서 재사용 비용을 줄이는 데 쓰입니다.'],
      ['공식 참고가', '공개 공식 가격과 비교하기 위한 항목입니다. 실제 과금은 API-Route 요금과 사용 로그를 따릅니다.'],
    ],
    calculator: {
      title: '토큰 비용 계산기',
      description: '토큰 과금 모델을 선택하고 요청당 평균 사용량과 요청 횟수를 입력하세요.',
      model: '모델',
      inputTokens: '평균 입력 토큰',
      outputTokens: '평균 출력 토큰',
      cacheReadTokens: '평균 캐시 읽기 토큰(선택)',
      cacheCreationTokens: '평균 캐시 생성 토큰(선택)',
      requests: '요청 횟수',
      estimatedTotal: '예상 총비용',
      estimateNote: '예상값이며 실제 요금은 사용 로그를 기준으로 합니다. 캐시 생성은 표의 기본 캐시 생성 요금을 사용합니다.',
      unavailable: '계산에 사용할 수 있는 토큰 과금 모델이 없습니다.',
    },
    faqTitle: 'AI API 요금 비교 FAQ',
    questions: [
      ['OpenAI, Claude, Gemini API 요금은 어떻게 비교하나요?', '입력과 출력 토큰 단가를 먼저 보고 캐시 요금, 호출당 과금, 문맥 길이, 예상 요청량을 함께 확인하세요.'],
      ['AI API 토큰 비용은 어떻게 계산하나요?', '텍스트 모델은 입력 비용, 출력 비용, 캐시 관련 비용을 합산합니다. 이미지, 오디오, 영상 모델은 표의 사양 또는 호출당 요금을 따릅니다.'],
      ['공식 참고 가격은 왜 표시하나요?', '공개된 공급자 가격과 비교하기 위한 정보입니다. 실제 과금은 API-Route 요금, 계정 기록, 사용 로그를 따릅니다.'],
    ],
  },
};

export function getPricingCopy(language) {
  return PRICING_COPY[language] || PRICING_COPY.en;
}
